function hRD = plugin_rd()
% Reference design definition
% Construct reference design object
hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Xilinx Vivado');
hRD.ReferenceDesignName = 'AMER design with HiTerm';
hRD.BoardName = 'AMER_HIL';
% Tool information
hRD.SupportedToolVersion = {'2018.2.2'};
%% Add custom design files
% add custom Vivado design
hRD.addCustomVivadoDesign( ...
    'CustomBlockDesignTcl', 'design_1.tcl');

hRD.addIPRepository('IPListFunction', 'vivado.iplist', 'NotExistMessage', 'IP repository not found');

% add custom files, use relative path
hRD.CustomConstraints = {'amer_top_constraint.xdc'};

%% Add interfaces
% add clock interface
hRD.addClockInterface( ...
    'ClockConnection',      'clk_wiz_0/clk', ...
    'ResetConnection',      'proc_sys_reset_0/peripheral_aresetn',...
    'DefaultFrequencyMHz',  20,...
    'MinFrequencyMHz',      20,...
    'MaxFrequencyMHz',      20,...
    'ClockNumber',          2,...
    'ClockModuleInstance',  'clk_wiz_0');

hRD.EmbeddedCoderSupportPackage = hdlcoder.EmbeddedCoderSupportPackage.None;

hRD.addInternalIOInterface(...
    'InterfaceID','Serial IO extenstion output',... 
    'InterfaceType', 'OUT',...
    'PortName', 'IOextOut', ...
    'PortWidth', 8,...
    'InterfaceConnection', 'ioexp_0/outdata');

hRD.addInternalIOInterface(...
    'InterfaceID','Serial IO extenstion input',... 
    'InterfaceType', 'IN',...
    'PortName', 'IOextIn', ...
    'PortWidth', 8,...
    'InterfaceConnection', 'ioexp_0/indata');

hRD.addInternalIOInterface(...
    'InterfaceID','Sigma-delta MUX A',... 
    'InterfaceType', 'OUT',...
    'PortName', 'SDMuxA', ...
    'PortWidth', 8,...
    'InterfaceConnection', 'sd_multiplexer_0/sdac_a');

hRD.addInternalIOInterface(...
    'InterfaceID','Sigma-delta MUX B',... 
    'InterfaceType', 'OUT',...
    'PortName', 'SDMuxB', ...
    'PortWidth', 8,...
    'InterfaceConnection', 'sd_multiplexer_0/sdac_b');

%% Hiterm ports
% global DataPortNum ParamPortNum TestPointNum TunableParamNum
%
DataPortNum = length(find_system(bdroot,'SearchDepth',1,'regexp','on','Name','ht_Data'));
ParamPortNum = length(find_system(bdroot,'SearchDepth',1,'regexp','on','Name','ht_Param'));
TestPointNum = 0;
sig = find_system(bdroot,'FindAll','on','Type','line'); 
for ii=1:length(sig), 
    if(get(sig(ii),'TestPoint'))
        TestPointNum = TestPointNum + 1; 
    end;
end;

h = find_system(get_param(bdroot,'Handle'),'regexp','on','Name','tp_');
TunableParamNum = length(h);

%for ii = 1:length(h),
%   if(strcmp(eval([get(h(ii),'Value') '.CoderInfo.StorageClass']), 'ExportedGlobal'))
%        TunableParamNum = TunableParamNum + 1; 
%   end;    
%end;

for ii = 0:DataPortNum + TestPointNum - 1, 
hRD.addInternalIOInterface(...
    'InterfaceID',['Data' num2str(ii)],... 
    'InterfaceType', 'OUT',...
    'PortName', ['Data' num2str(ii)], ...
    'PortWidth', 32,...
    'InterfaceConnection', ['mon_module_0/data' num2str(ii)]);
end;
for ii = 0:ParamPortNum + TunableParamNum -1, 
hRD.addInternalIOInterface(...
    'InterfaceID',['Param' num2str(ii)],... 
    'InterfaceType', 'IN',...
    'PortName', ['Param' num2str(ii)], ...
    'PortWidth', 32,...
    'InterfaceConnection', ['mon_module_0/param' num2str(ii)]);
end;

% hRD.addInternalIOInterface(...
%     'InterfaceID','Data0',... 
%     'InterfaceType', 'OUT',...
%     'PortName', 'Data0', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/data0');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Data1',... 
%     'InterfaceType', 'OUT',...
%     'PortName', 'Data1', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/data1');
% 
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param0',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param0', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param0');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param1',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param1', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param1');

% hRD.addInternalIOInterface(...
%     'InterfaceID','Param2',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param2', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param2');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param3',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param3', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param3');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param4',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param4', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param4');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param5',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param5', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param5');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param6',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param6', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param6');
% 
% hRD.addInternalIOInterface(...
%     'InterfaceID','Param7',... 
%     'InterfaceType', 'IN',...
%     'PortName', 'Param7', ...
%     'PortWidth', 32,...
%     'InterfaceConnection', 'mon_module_0/param7');
