-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_RLUb_DTFX.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_RLUb_DTFX
-- Source Path: RLUb_HIL/RLUb_DTFX
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_RLUb_DTFX IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        control_Inport_1_signal1_GH       :   IN    std_logic;
        control_Inport_1_signal1_GL       :   IN    std_logic;
        control_Inport_1_gate_en          :   IN    std_logic;
        par_Inport_2_Udc                  :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        par_Inport_2_Ub                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        y_Outport_1_Iout                  :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
        y_Outport_1_Vout                  :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        y_Outport_1_Udc                   :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        y_Outport_1_Ub                    :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En16
        );
END RLUb_HIL_ip_src_RLUb_DTFX;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_RLUb_DTFX IS

  -- Signals
  SIGNAL s                                : std_logic;
  SIGNAL GH                               : std_logic;
  SIGNAL s_1                              : std_logic;
  SIGNAL gate_en                          : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL s_2                              : std_logic;
  SIGNAL GL                               : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL Constant_out1                    : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL s_3                              : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Udc                              : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL s_4                              : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Ub                               : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Data_Type_Conversion_out1        : signed(24 DOWNTO 0);  -- sfix25_En17
  SIGNAL Gain1_mul_temp                   : signed(49 DOWNTO 0);  -- sfix50_En57
  SIGNAL Gain1_out1                       : signed(24 DOWNTO 0);  -- sfix25_En34
  SIGNAL Delay_out1                       : signed(41 DOWNTO 0);  -- sfix42_En34
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Switch_out1                      : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Sum_out1                         : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Gain_mul_temp                    : signed(49 DOWNTO 0);  -- sfix50_En53
  SIGNAL Gain_out1                        : signed(24 DOWNTO 0);  -- sfix25_En29
  SIGNAL Sum1_stage2_sub_cast             : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Sum1_stage2_sub_cast_1           : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Sum1_op_stage2                   : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Sum1_stage3_add_cast             : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Sum1_stage3_add_temp             : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Sum1_out1                        : signed(41 DOWNTO 0);  -- sfix42_En34

BEGIN
  s <= control_Inport_1_signal1_GH;

  GH <= s;

  s_1 <= control_Inport_1_gate_en;

  gate_en <= s_1;

  Logical_Operator3_out1 <= GH AND gate_en;

  s_2 <= control_Inport_1_signal1_GL;

  GL <= s_2;

  Logical_Operator4_out1 <=  NOT (GL AND gate_en);

  Constant_out1 <= to_signed(16#0000000#, 25);

  s_3 <= signed(par_Inport_2_Udc);

  Udc <= s_3;

  s_4 <= signed(par_Inport_2_Ub);

  Ub <= s_4;

  Gain1_mul_temp <= to_signed(16#0A7C5AC#, 25) * Data_Type_Conversion_out1;
  Gain1_out1 <= Gain1_mul_temp(47 DOWNTO 23);

  
  Compare_To_Zero_out1 <= '1' WHEN Delay_out1 < to_signed(0, 42) ELSE
      '0';

  Logical_Operator_out1 <= Logical_Operator4_out1 AND Compare_To_Zero_out1;

  Logical_Operator1_out1 <= Logical_Operator3_out1 OR Logical_Operator_out1;

  
  switch_compare_1 <= '1' WHEN Logical_Operator1_out1 > '0' ELSE
      '0';

  
  Switch_out1 <= Constant_out1 WHEN switch_compare_1 = '0' ELSE
      Udc;

  Sum_out1 <= Switch_out1 - Ub;

  Gain_mul_temp <= to_signed(16#0D1B717#, 25) * Sum_out1;
  Gain_out1 <= Gain_mul_temp(48 DOWNTO 24);

  Sum1_stage2_sub_cast <= resize(Gain_out1 & '0' & '0' & '0' & '0' & '0', 43);
  Sum1_stage2_sub_cast_1 <= resize(Gain1_out1, 43);
  Sum1_op_stage2 <= Sum1_stage2_sub_cast - Sum1_stage2_sub_cast_1;

  Sum1_stage3_add_cast <= resize(Delay_out1, 43);
  Sum1_stage3_add_temp <= Sum1_op_stage2 + Sum1_stage3_add_cast;
  Sum1_out1 <= Sum1_stage3_add_temp(41 DOWNTO 0);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(0, 42);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Sum1_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Data_Type_Conversion_out1 <= Delay_out1(41 DOWNTO 17);

  y_Outport_1_Iout <= std_logic_vector(Data_Type_Conversion_out1);

  y_Outport_1_Vout <= std_logic_vector(Switch_out1);

  y_Outport_1_Udc <= par_Inport_2_Udc;

  y_Outport_1_Ub <= par_Inport_2_Ub;

END rtl;

