%hdlsetuptoolpath('ToolName','Xilinx ISE','ToolPath',...
% 'C:\Xilinx\14.7\ISE_DS\ISE\bin\nt64\ise.exe');
% hdlsetuptoolpath('ToolName', 'Xilinx Vivado', ...
%  'ToolPath', 'C:\Xilinx\Vivado\2017.2\bin\vivado.bat');
hdlsetuptoolpath('ToolName', 'Xilinx Vivado', ...
 'ToolPath', 'C:\Xilinx\Vivado\2018.2\bin\vivado.bat');