-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip.vhd
-- Created: 2026-03-27 14:58:46
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip
-- Source Path: RLUb_HIL_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        IOextIn                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        Param0                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param1                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param2                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param3                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param4                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param5                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param6                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Param7                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ZyboBTN                           :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        ZyboSW                            :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlH                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlL                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        IOextOut                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        SDMuxA                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        SDMuxB                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        Data0                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        Data1                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        Data2                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        Data3                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        Data4                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ZyboLED                           :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Status                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Fail                              :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        QEP                               :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
        );
END RLUb_HIL_ip;


ARCHITECTURE rtl OF RLUb_HIL_ip IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;  -- ufix1
          dut_enable                      :   IN    std_logic;  -- ufix1
          ZyboBTN                         :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          ZyboSW                          :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlH                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlL                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          IOextIn                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          ht_Param0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          ZyboLED                         :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          SD_MUX_A                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          SD_MUX_B                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          IOextOut                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          Status                          :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          Fail                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          QEP                             :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          ht_Data0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data4                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_dut
    USE ENTITY work.RLUb_HIL_ip_dut(rtl);

  -- Signals
  SIGNAL dut_enable                       : std_logic;  -- ufix1
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL ZyboLED_sig                      : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL SD_MUX_A_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL SD_MUX_B_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL IOextOut_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Status_sig                       : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL Fail_sig                         : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL QEP_sig                          : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL ht_Data0_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data1_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data2_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data3_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data4_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_RLUb_HIL_ip_dut_inst : RLUb_HIL_ip_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset_cm,  -- ufix1
              dut_enable => dut_enable,  -- ufix1
              ZyboBTN => ZyboBTN,  -- ufix3
              ZyboSW => ZyboSW,  -- ufix4
              CtrlH => CtrlH,  -- ufix4
              CtrlL => CtrlL,  -- ufix4
              IOextIn => IOextIn,  -- ufix8
              ht_Param0 => Param0,  -- ufix32
              ht_Param1 => Param1,  -- ufix32
              ht_Param2 => Param2,  -- ufix32
              ht_Param3 => Param3,  -- ufix32
              ht_Param4 => Param4,  -- ufix32
              ht_Param5 => Param5,  -- ufix32
              ht_Param6 => Param6,  -- ufix32
              ht_Param7 => Param7,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              ZyboLED => ZyboLED_sig,  -- ufix4
              SD_MUX_A => SD_MUX_A_sig,  -- ufix8
              SD_MUX_B => SD_MUX_B_sig,  -- ufix8
              IOextOut => IOextOut_sig,  -- ufix8
              Status => Status_sig,  -- ufix4
              Fail => Fail_sig,  -- ufix4
              QEP => QEP_sig,  -- ufix4
              ht_Data0 => ht_Data0_sig,  -- ufix32
              ht_Data1 => ht_Data1_sig,  -- ufix32
              ht_Data2 => ht_Data2_sig,  -- ufix32
              ht_Data3 => ht_Data3_sig,  -- ufix32
              ht_Data4 => ht_Data4_sig  -- ufix32
              );

  dut_enable <= '1';

  reset_cm <=  NOT IPCORE_RESETN;

  IOextOut <= IOextOut_sig;

  SDMuxA <= SD_MUX_A_sig;

  SDMuxB <= SD_MUX_B_sig;

  Data0 <= ht_Data0_sig;

  Data1 <= ht_Data1_sig;

  Data2 <= ht_Data2_sig;

  Data3 <= ht_Data3_sig;

  Data4 <= ht_Data4_sig;

  ZyboLED <= ZyboLED_sig;

  Status <= Status_sig;

  Fail <= Fail_sig;

  QEP <= QEP_sig;

END rtl;

