-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Subsystem2.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Subsystem2
-- Source Path: RLUb_HIL/HitermInputs/Subsystem2
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_Subsystem2 IS
  PORT( Vio                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Status_Status4                    :   OUT   std_logic;  -- ufix1
        Status_Status3                    :   OUT   std_logic;  -- ufix1
        Status_Status2                    :   OUT   std_logic;  -- ufix1
        Status_Status1                    :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_Subsystem2;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Subsystem2 IS

  -- Signals
  SIGNAL Vio_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Status4                          : std_logic;  -- ufix1
  SIGNAL Status3                          : std_logic;  -- ufix1
  SIGNAL Status2                          : std_logic;  -- ufix1
  SIGNAL Status1                          : std_logic;  -- ufix1

BEGIN
  Vio_unsigned <= unsigned(Vio);

  Status4 <= Vio_unsigned(3);

  Status_Status4 <= Status4;

  Status3 <= Vio_unsigned(2);

  Status_Status3 <= Status3;

  Status2 <= Vio_unsigned(1);

  Status_Status2 <= Status2;

  Status1 <= Vio_unsigned(0);

  Status_Status1 <= Status1;

END rtl;

