-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Counter.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Counter
-- Source Path: RLUb_HIL/HitermOutputs/Counter
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_Counter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        limit                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Cnt                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END RLUb_HIL_ip_src_Counter;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Counter IS

  -- Signals
  SIGNAL limit_unsigned                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant2_out1                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_out1                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Increment_Stored_Integer_out1    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Switch_out1                      : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  limit_unsigned <= unsigned(limit);

  Constant2_out1 <= to_unsigned(16#0000#, 16);

  Increment_Stored_Integer_out1 <= Unit_Delay_out1 + to_unsigned(16#0001#, 16);

  
  Relational_Operator_relop1 <= '1' WHEN limit_unsigned <= Increment_Stored_Integer_out1 ELSE
      '0';

  
  switch_compare_1 <= '1' WHEN Relational_Operator_relop1 > '0' ELSE
      '0';

  
  Switch_out1 <= Increment_Stored_Integer_out1 WHEN switch_compare_1 = '0' ELSE
      Constant2_out1;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Cnt <= std_logic_vector(Unit_Delay_out1);

END rtl;

