-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_GateSignals.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_GateSignals
-- Source Path: RLUb_HIL/AmerInputs/GateSignals
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_GateSignals IS
  PORT( CtrlH                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlL                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        Ctrl_GH_H4                        :   OUT   std_logic;  -- ufix1
        Ctrl_GH_H3                        :   OUT   std_logic;  -- ufix1
        Ctrl_GH_H2                        :   OUT   std_logic;  -- ufix1
        Ctrl_GH_H1                        :   OUT   std_logic;  -- ufix1
        Ctrl_GL_L4                        :   OUT   std_logic;  -- ufix1
        Ctrl_GL_L3                        :   OUT   std_logic;  -- ufix1
        Ctrl_GL_L2                        :   OUT   std_logic;  -- ufix1
        Ctrl_GL_L1                        :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_GateSignals;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_GateSignals IS

  -- Signals
  SIGNAL CtrlH_unsigned                   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL H4                               : std_logic;  -- ufix1
  SIGNAL H3                               : std_logic;  -- ufix1
  SIGNAL H2                               : std_logic;  -- ufix1
  SIGNAL H1                               : std_logic;  -- ufix1
  SIGNAL CtrlL_unsigned                   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL L4                               : std_logic;  -- ufix1
  SIGNAL L3                               : std_logic;  -- ufix1
  SIGNAL L2                               : std_logic;  -- ufix1
  SIGNAL L1                               : std_logic;  -- ufix1

BEGIN
  CtrlH_unsigned <= unsigned(CtrlH);

  H4 <= CtrlH_unsigned(3);

  Ctrl_GH_H4 <= H4;

  H3 <= CtrlH_unsigned(2);

  Ctrl_GH_H3 <= H3;

  H2 <= CtrlH_unsigned(1);

  Ctrl_GH_H2 <= H2;

  H1 <= CtrlH_unsigned(0);

  Ctrl_GH_H1 <= H1;

  CtrlL_unsigned <= unsigned(CtrlL);

  L4 <= CtrlL_unsigned(3);

  Ctrl_GL_L4 <= L4;

  L3 <= CtrlL_unsigned(2);

  Ctrl_GL_L3 <= L3;

  L2 <= CtrlL_unsigned(1);

  Ctrl_GL_L2 <= L2;

  L1 <= CtrlL_unsigned(0);

  Ctrl_GL_L1 <= L1;

END rtl;

