-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_ZyboIO.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_ZyboIO
-- Source Path: RLUb_HIL/AmerInputs/ZyboIO
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_ZyboIO IS
  PORT( BTN                               :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        SW                                :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        ZyboBTN_BTN3                      :   OUT   std_logic;  -- ufix1
        ZyboBTN_BTN2                      :   OUT   std_logic;  -- ufix1
        ZyboBTN_BTN1                      :   OUT   std_logic;  -- ufix1
        ZyboSW_SW3                        :   OUT   std_logic;  -- ufix1
        ZyboSW_SW2                        :   OUT   std_logic;  -- ufix1
        ZyboSW_SW1                        :   OUT   std_logic;  -- ufix1
        ZyboSW_SW0                        :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_ZyboIO;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_ZyboIO IS

  -- Signals
  SIGNAL BTN_unsigned                     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL BTN3                             : std_logic;  -- ufix1
  SIGNAL BTN2                             : std_logic;  -- ufix1
  SIGNAL BTN1                             : std_logic;  -- ufix1
  SIGNAL SW_unsigned                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL SW3                              : std_logic;  -- ufix1
  SIGNAL SW2                              : std_logic;  -- ufix1
  SIGNAL SW1                              : std_logic;  -- ufix1
  SIGNAL SW0                              : std_logic;  -- ufix1

BEGIN
  BTN_unsigned <= unsigned(BTN);

  BTN3 <= BTN_unsigned(2);

  ZyboBTN_BTN3 <= BTN3;

  BTN2 <= BTN_unsigned(1);

  ZyboBTN_BTN2 <= BTN2;

  BTN1 <= BTN_unsigned(0);

  ZyboBTN_BTN1 <= BTN1;

  SW_unsigned <= unsigned(SW);

  SW3 <= SW_unsigned(3);

  ZyboSW_SW3 <= SW3;

  SW2 <= SW_unsigned(2);

  ZyboSW_SW2 <= SW2;

  SW1 <= SW_unsigned(1);

  ZyboSW_SW1 <= SW1;

  SW0 <= SW_unsigned(0);

  ZyboSW_SW0 <= SW0;

END rtl;

