-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_SignedScale.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_SignedScale
-- Source Path: RLUb_HIL/SignalMUX/AnalogOut/SignedScale
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_SignedScale IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END RLUb_HIL_ip_src_SignedScale;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_SignedScale IS

  -- Signals
  SIGNAL kconst                           : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL kconst_1                         : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL In1_signed                       : signed(24 DOWNTO 0);  -- sfix25_En17
  SIGNAL In1_1                            : signed(24 DOWNTO 0);  -- sfix25_En17
  SIGNAL FS_out1                          : signed(49 DOWNTO 0);  -- sfix50_En31
  SIGNAL FS_out1_1                        : signed(49 DOWNTO 0);  -- sfix50_En31
  SIGNAL FS_out1_2                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Bias_const_val_1                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Bias_out1                        : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  kconst <= to_signed(16#083126F#, 25);

  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      kconst_1 <= to_signed(16#0000000#, 25);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        kconst_1 <= kconst;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  In1_signed <= signed(In1);

  HwModeRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1_1 <= to_signed(16#0000000#, 25);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In1_1 <= In1_signed;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  FS_out1 <= kconst_1 * In1_1;

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      FS_out1_1 <= to_signed(0, 50);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        FS_out1_1 <= FS_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  FS_out1_2 <= X"7FFF" WHEN (FS_out1_1(49) = '0') AND (FS_out1_1(48 DOWNTO 46) /= "000") ELSE
      X"8000" WHEN (FS_out1_1(49) = '1') AND (FS_out1_1(48 DOWNTO 46) /= "111") ELSE
      FS_out1_1(46 DOWNTO 31);

  Data_Type_Conversion_out1 <= unsigned(FS_out1_2);

  Bias_const_val_1 <= to_unsigned(16#8000#, 16);

  Bias_out1 <= Data_Type_Conversion_out1 + Bias_const_val_1;

  Out1 <= std_logic_vector(Bias_out1);

END rtl;

