-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Subsystem3.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Subsystem3
-- Source Path: RLUb_HIL/HitermInputs/Subsystem3
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_Subsystem3 IS
  PORT( Vio                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Fail_Fail4                        :   OUT   std_logic;  -- ufix1
        Fail_Fail3                        :   OUT   std_logic;  -- ufix1
        Fail_Fail2                        :   OUT   std_logic;  -- ufix1
        Fail_Fail1                        :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_Subsystem3;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Subsystem3 IS

  -- Signals
  SIGNAL Vio_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Fail4                            : std_logic;  -- ufix1
  SIGNAL Fail3                            : std_logic;  -- ufix1
  SIGNAL Fail2                            : std_logic;  -- ufix1
  SIGNAL Fail1                            : std_logic;  -- ufix1

BEGIN
  Vio_unsigned <= unsigned(Vio);

  Fail4 <= Vio_unsigned(3);

  Fail_Fail4 <= Fail4;

  Fail3 <= Vio_unsigned(2);

  Fail_Fail3 <= Fail3;

  Fail2 <= Vio_unsigned(1);

  Fail_Fail2 <= Fail2;

  Fail1 <= Vio_unsigned(0);

  Fail_Fail1 <= Fail1;

END rtl;

