-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_AnalogOut.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_AnalogOut
-- Source Path: RLUb_HIL/SignalMUX/AnalogOut
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.RLUb_HIL_ip_src_RLUb_HIL_pkg.ALL;

ENTITY RLUb_HIL_ip_src_AnalogOut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        model_out_Iout                    :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
        model_out_Vout                    :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        model_out_Udc                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        model_out_Ub                      :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        ANA_CH7                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH6                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH5                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH4                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH3                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH1                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANA_CH0                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH7                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH6                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH5                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH4                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH3                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH1                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        ANB_CH0                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END RLUb_HIL_ip_src_AnalogOut;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_AnalogOut IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_UnsignedScale1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_UnsignedScale
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_SignedScale
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_UnsignedScale1
    USE ENTITY work.RLUb_HIL_ip_src_UnsignedScale1(rtl);

  FOR ALL : RLUb_HIL_ip_src_UnsignedScale
    USE ENTITY work.RLUb_HIL_ip_src_UnsignedScale(rtl);

  FOR ALL : RLUb_HIL_ip_src_SignedScale
    USE ENTITY work.RLUb_HIL_ip_src_SignedScale(rtl);

  -- Signals
  SIGNAL Constant3_out1                   : vector_of_unsigned16(0 TO 4);  -- uint16 [5]
  SIGNAL Constant3_out1_0                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL delayMatch_reg                   : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL CH7                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant3_out1_1                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL delayMatch1_reg                  : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL CH6                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant3_out1_2                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL delayMatch2_reg                  : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL CH5                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant3_out1_3                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL delayMatch3_reg                  : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL CH4                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant3_out1_4                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL delayMatch4_reg                  : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL CH3                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Ub                               : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL CH2                              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Udc                              : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL CH1                              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Iout                             : signed(24 DOWNTO 0);  -- sfix25_En17
  SIGNAL CH0                              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Constant1_out1                   : vector_of_unsigned16(0 TO 7);  -- uint16 [8]
  SIGNAL CH7_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH6_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH5_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH4_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH3_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH2_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH1_1                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL CH0_1                            : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  u_UnsignedScale1 : RLUb_HIL_ip_src_UnsignedScale1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => std_logic_vector(Ub),  -- sfix25_En16
              Out1 => CH2  -- uint16
              );

  u_UnsignedScale : RLUb_HIL_ip_src_UnsignedScale
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => std_logic_vector(Udc),  -- sfix25_En16
              Out1 => CH1  -- uint16
              );

  u_SignedScale : RLUb_HIL_ip_src_SignedScale
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => std_logic_vector(Iout),  -- sfix25_En17
              Out1 => CH0  -- uint16
              );

  Constant3_out1(0) <= to_unsigned(16#0000#, 16);
  Constant3_out1(1) <= to_unsigned(16#0000#, 16);
  Constant3_out1(2) <= to_unsigned(16#0000#, 16);
  Constant3_out1(3) <= to_unsigned(16#0000#, 16);
  Constant3_out1(4) <= to_unsigned(16#0000#, 16);

  Constant3_out1_0 <= Constant3_out1(0);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= Constant3_out1_0;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  CH7 <= delayMatch_reg(1);

  ANA_CH7 <= std_logic_vector(CH7);

  Constant3_out1_1 <= Constant3_out1(1);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch1_reg(0) <= Constant3_out1_1;
        delayMatch1_reg(1) <= delayMatch1_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  CH6 <= delayMatch1_reg(1);

  ANA_CH6 <= std_logic_vector(CH6);

  Constant3_out1_2 <= Constant3_out1(2);

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch2_reg <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch2_reg(0) <= Constant3_out1_2;
        delayMatch2_reg(1) <= delayMatch2_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch2_process;

  CH5 <= delayMatch2_reg(1);

  ANA_CH5 <= std_logic_vector(CH5);

  Constant3_out1_3 <= Constant3_out1(3);

  delayMatch3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch3_reg <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch3_reg(0) <= Constant3_out1_3;
        delayMatch3_reg(1) <= delayMatch3_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch3_process;

  CH4 <= delayMatch3_reg(1);

  ANA_CH4 <= std_logic_vector(CH4);

  Constant3_out1_4 <= Constant3_out1(4);

  delayMatch4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch4_reg <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch4_reg(0) <= Constant3_out1_4;
        delayMatch4_reg(1) <= delayMatch4_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch4_process;

  CH3 <= delayMatch4_reg(1);

  ANA_CH3 <= std_logic_vector(CH3);

  Ub <= signed(model_out_Ub);

  Udc <= signed(model_out_Udc);

  Iout <= signed(model_out_Iout);

  Constant1_out1(0) <= to_unsigned(16#0000#, 16);
  Constant1_out1(1) <= to_unsigned(16#0000#, 16);
  Constant1_out1(2) <= to_unsigned(16#0000#, 16);
  Constant1_out1(3) <= to_unsigned(16#0000#, 16);
  Constant1_out1(4) <= to_unsigned(16#0000#, 16);
  Constant1_out1(5) <= to_unsigned(16#0000#, 16);
  Constant1_out1(6) <= to_unsigned(16#0000#, 16);
  Constant1_out1(7) <= to_unsigned(16#0000#, 16);

  ANB_CH7 <= std_logic_vector(Constant1_out1(0));

  ANB_CH6 <= std_logic_vector(Constant1_out1(1));

  ANB_CH5 <= std_logic_vector(Constant1_out1(2));

  ANB_CH4 <= std_logic_vector(Constant1_out1(3));

  ANB_CH3 <= std_logic_vector(Constant1_out1(4));

  ANB_CH2 <= std_logic_vector(Constant1_out1(5));

  ANB_CH1 <= std_logic_vector(Constant1_out1(6));

  ANB_CH0 <= std_logic_vector(Constant1_out1(7));

  ANA_CH2 <= CH2;

  ANA_CH1 <= CH1;

  ANA_CH0 <= CH0;

END rtl;

