-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Subsystem1.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Subsystem1
-- Source Path: RLUb_HIL/HitermInputs/Subsystem1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_Subsystem1 IS
  PORT( Vio                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        SlowOut_OUT7                      :   OUT   std_logic;  -- ufix1
        SlowOut_OUT6                      :   OUT   std_logic;  -- ufix1
        SlowOut_OUT5                      :   OUT   std_logic;  -- ufix1
        SlowOut_OUT4                      :   OUT   std_logic;  -- ufix1
        SlowOut_OUT3                      :   OUT   std_logic;  -- ufix1
        SlowOut_OUT2                      :   OUT   std_logic;  -- ufix1
        SlowOut_OUT1                      :   OUT   std_logic;  -- ufix1
        SlowOut_HILboardRLED              :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_Subsystem1;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Subsystem1 IS

  -- Signals
  SIGNAL Vio_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL OUT7                             : std_logic;  -- ufix1
  SIGNAL OUT6                             : std_logic;  -- ufix1
  SIGNAL OUT5                             : std_logic;  -- ufix1
  SIGNAL OUT4                             : std_logic;  -- ufix1
  SIGNAL OUT3                             : std_logic;  -- ufix1
  SIGNAL OUT2                             : std_logic;  -- ufix1
  SIGNAL OUT1                             : std_logic;  -- ufix1
  SIGNAL HILboardRLED                     : std_logic;  -- ufix1

BEGIN
  Vio_unsigned <= unsigned(Vio);

  OUT7 <= Vio_unsigned(7);

  SlowOut_OUT7 <= OUT7;

  OUT6 <= Vio_unsigned(6);

  SlowOut_OUT6 <= OUT6;

  OUT5 <= Vio_unsigned(5);

  SlowOut_OUT5 <= OUT5;

  OUT4 <= Vio_unsigned(4);

  SlowOut_OUT4 <= OUT4;

  OUT3 <= Vio_unsigned(3);

  SlowOut_OUT3 <= OUT3;

  OUT2 <= Vio_unsigned(2);

  SlowOut_OUT2 <= OUT2;

  OUT1 <= Vio_unsigned(1);

  SlowOut_OUT1 <= OUT1;

  HILboardRLED <= Vio_unsigned(0);

  SlowOut_HILboardRLED <= HILboardRLED;

END rtl;

