open_system('RLUb_HIL');
open_system('gm_RLUb_HIL');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Compare To Zero', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Compare To Zero', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Logical Operator', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Logical Operator', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Logical Operator1', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Logical Operator1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Switch', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Switch', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Sum', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Sum', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Gain', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Gain', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Gain1', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Gain1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Data Type Conversion', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Data Type Conversion', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Gain1', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Gain1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Sum1', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Sum1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Delay', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Delay', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Compare To Zero', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Compare To Zero', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Logical Operator', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Logical Operator', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Logical Operator1', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Logical Operator1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Switch', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Switch', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Sum', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Sum', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Gain', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Gain', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('RLUb_HIL/RLUb_DTFX/Sum1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Delay', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Delay', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_RLUb_HIL/RLUb_DTFX/Data Type Conversion', 'user2');
hilite_system('RLUb_HIL/RLUb_DTFX/Data Type Conversion', 'user2');
