-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Subsystem4.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Subsystem4
-- Source Path: RLUb_HIL/HitermInputs/Subsystem4
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_Subsystem4 IS
  PORT( Vio                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Encoder_I                         :   OUT   std_logic;  -- ufix1
        Encoder_Z                         :   OUT   std_logic;  -- ufix1
        Encoder_B                         :   OUT   std_logic;  -- ufix1
        Encoder_A                         :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_Subsystem4;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Subsystem4 IS

  -- Signals
  SIGNAL Vio_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL I                                : std_logic;  -- ufix1
  SIGNAL Z                                : std_logic;  -- ufix1
  SIGNAL B                                : std_logic;  -- ufix1
  SIGNAL A                                : std_logic;  -- ufix1

BEGIN
  Vio_unsigned <= unsigned(Vio);

  I <= Vio_unsigned(3);

  Encoder_I <= I;

  Z <= Vio_unsigned(2);

  Encoder_Z <= Z;

  B <= Vio_unsigned(1);

  Encoder_B <= B;

  A <= Vio_unsigned(0);

  Encoder_A <= A;

END rtl;

