-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_AmerInputs.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_AmerInputs
-- Source Path: RLUb_HIL/AmerInputs
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_AmerInputs IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        ZyboBTN                           :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        ZyboSW                            :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlH                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlL                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        IOextIn                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        AmerIn_ZyboBTN_BTN3               :   OUT   std_logic;  -- ufix1
        AmerIn_ZyboBTN_BTN2               :   OUT   std_logic;  -- ufix1
        AmerIn_ZyboBTN_BTN1               :   OUT   std_logic;  -- ufix1
        AmerIn_ZyboSW_SW3                 :   OUT   std_logic;  -- ufix1
        AmerIn_ZyboSW_SW2                 :   OUT   std_logic;  -- ufix1
        AmerIn_ZyboSW_SW1                 :   OUT   std_logic;  -- ufix1
        AmerIn_ZyboSW_SW0                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H4                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H3                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H2                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H1                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L4                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L3                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L2                 :   OUT   std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L1                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN7                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN6                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN5                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN4                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN3                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN2                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_IN1                 :   OUT   std_logic;  -- ufix1
        AmerIn_SlowIn_HILboardSW          :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_AmerInputs;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_AmerInputs IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_ZyboIO
    PORT( BTN                             :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          SW                              :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          ZyboBTN_BTN3                    :   OUT   std_logic;  -- ufix1
          ZyboBTN_BTN2                    :   OUT   std_logic;  -- ufix1
          ZyboBTN_BTN1                    :   OUT   std_logic;  -- ufix1
          ZyboSW_SW3                      :   OUT   std_logic;  -- ufix1
          ZyboSW_SW2                      :   OUT   std_logic;  -- ufix1
          ZyboSW_SW1                      :   OUT   std_logic;  -- ufix1
          ZyboSW_SW0                      :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_GateSignals
    PORT( CtrlH                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlL                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          Ctrl_GH_H4                      :   OUT   std_logic;  -- ufix1
          Ctrl_GH_H3                      :   OUT   std_logic;  -- ufix1
          Ctrl_GH_H2                      :   OUT   std_logic;  -- ufix1
          Ctrl_GH_H1                      :   OUT   std_logic;  -- ufix1
          Ctrl_GL_L4                      :   OUT   std_logic;  -- ufix1
          Ctrl_GL_L3                      :   OUT   std_logic;  -- ufix1
          Ctrl_GL_L2                      :   OUT   std_logic;  -- ufix1
          Ctrl_GL_L1                      :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_IO_Extension_Inputs
    PORT( In1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          SlowIn_IN7                      :   OUT   std_logic;  -- ufix1
          SlowIn_IN6                      :   OUT   std_logic;  -- ufix1
          SlowIn_IN5                      :   OUT   std_logic;  -- ufix1
          SlowIn_IN4                      :   OUT   std_logic;  -- ufix1
          SlowIn_IN3                      :   OUT   std_logic;  -- ufix1
          SlowIn_IN2                      :   OUT   std_logic;  -- ufix1
          SlowIn_IN1                      :   OUT   std_logic;  -- ufix1
          SlowIn_HILboardSW               :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_ZyboIO
    USE ENTITY work.RLUb_HIL_ip_src_ZyboIO(rtl);

  FOR ALL : RLUb_HIL_ip_src_GateSignals
    USE ENTITY work.RLUb_HIL_ip_src_GateSignals(rtl);

  FOR ALL : RLUb_HIL_ip_src_IO_Extension_Inputs
    USE ENTITY work.RLUb_HIL_ip_src_IO_Extension_Inputs(rtl);

  -- Signals
  SIGNAL ZyboBTN_unsigned                 : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL ZyboSW_unsigned                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Delay_out1                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Delay1_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL ZyboIO_out1_BTN3                 : std_logic;  -- ufix1
  SIGNAL ZyboIO_out1_BTN2                 : std_logic;  -- ufix1
  SIGNAL ZyboIO_out1_BTN1                 : std_logic;  -- ufix1
  SIGNAL ZyboIO_out2_SW3                  : std_logic;  -- ufix1
  SIGNAL ZyboIO_out2_SW2                  : std_logic;  -- ufix1
  SIGNAL ZyboIO_out2_SW1                  : std_logic;  -- ufix1
  SIGNAL ZyboIO_out2_SW0                  : std_logic;  -- ufix1
  SIGNAL CtrlH_unsigned                   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL CtrlL_unsigned                   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Delay2_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Delay3_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL GateSignals_out1_GH_H4           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GH_H3           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GH_H2           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GH_H1           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GL_L4           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GL_L3           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GL_L2           : std_logic;  -- ufix1
  SIGNAL GateSignals_out1_GL_L1           : std_logic;  -- ufix1
  SIGNAL IOextIn_unsigned                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL IO_Extension_Inputs_out1_IN7     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_IN6     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_IN5     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_IN4     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_IN3     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_IN2     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_IN1     : std_logic;  -- ufix1
  SIGNAL IO_Extension_Inputs_out1_HILboardSW : std_logic;  -- ufix1

BEGIN
  u_ZyboIO : RLUb_HIL_ip_src_ZyboIO
    PORT MAP( BTN => std_logic_vector(Delay_out1),  -- ufix3
              SW => std_logic_vector(Delay1_out1),  -- ufix4
              ZyboBTN_BTN3 => ZyboIO_out1_BTN3,  -- ufix1
              ZyboBTN_BTN2 => ZyboIO_out1_BTN2,  -- ufix1
              ZyboBTN_BTN1 => ZyboIO_out1_BTN1,  -- ufix1
              ZyboSW_SW3 => ZyboIO_out2_SW3,  -- ufix1
              ZyboSW_SW2 => ZyboIO_out2_SW2,  -- ufix1
              ZyboSW_SW1 => ZyboIO_out2_SW1,  -- ufix1
              ZyboSW_SW0 => ZyboIO_out2_SW0  -- ufix1
              );

  u_GateSignals : RLUb_HIL_ip_src_GateSignals
    PORT MAP( CtrlH => std_logic_vector(Delay2_out1),  -- ufix4
              CtrlL => std_logic_vector(Delay3_out1),  -- ufix4
              Ctrl_GH_H4 => GateSignals_out1_GH_H4,  -- ufix1
              Ctrl_GH_H3 => GateSignals_out1_GH_H3,  -- ufix1
              Ctrl_GH_H2 => GateSignals_out1_GH_H2,  -- ufix1
              Ctrl_GH_H1 => GateSignals_out1_GH_H1,  -- ufix1
              Ctrl_GL_L4 => GateSignals_out1_GL_L4,  -- ufix1
              Ctrl_GL_L3 => GateSignals_out1_GL_L3,  -- ufix1
              Ctrl_GL_L2 => GateSignals_out1_GL_L2,  -- ufix1
              Ctrl_GL_L1 => GateSignals_out1_GL_L1  -- ufix1
              );

  u_IO_Extension_Inputs : RLUb_HIL_ip_src_IO_Extension_Inputs
    PORT MAP( In1 => std_logic_vector(Delay4_out1),  -- uint8
              SlowIn_IN7 => IO_Extension_Inputs_out1_IN7,  -- ufix1
              SlowIn_IN6 => IO_Extension_Inputs_out1_IN6,  -- ufix1
              SlowIn_IN5 => IO_Extension_Inputs_out1_IN5,  -- ufix1
              SlowIn_IN4 => IO_Extension_Inputs_out1_IN4,  -- ufix1
              SlowIn_IN3 => IO_Extension_Inputs_out1_IN3,  -- ufix1
              SlowIn_IN2 => IO_Extension_Inputs_out1_IN2,  -- ufix1
              SlowIn_IN1 => IO_Extension_Inputs_out1_IN1,  -- ufix1
              SlowIn_HILboardSW => IO_Extension_Inputs_out1_HILboardSW  -- ufix1
              );

  ZyboBTN_unsigned <= unsigned(ZyboBTN);

  ZyboSW_unsigned <= unsigned(ZyboSW);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= ZyboBTN_unsigned;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= ZyboSW_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  CtrlH_unsigned <= unsigned(CtrlH);

  CtrlL_unsigned <= unsigned(CtrlL);

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= CtrlH_unsigned;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= CtrlL_unsigned;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  IOextIn_unsigned <= unsigned(IOextIn);

  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= IOextIn_unsigned;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  AmerIn_ZyboBTN_BTN3 <= ZyboIO_out1_BTN3;

  AmerIn_ZyboBTN_BTN2 <= ZyboIO_out1_BTN2;

  AmerIn_ZyboBTN_BTN1 <= ZyboIO_out1_BTN1;

  AmerIn_ZyboSW_SW3 <= ZyboIO_out2_SW3;

  AmerIn_ZyboSW_SW2 <= ZyboIO_out2_SW2;

  AmerIn_ZyboSW_SW1 <= ZyboIO_out2_SW1;

  AmerIn_ZyboSW_SW0 <= ZyboIO_out2_SW0;

  AmerIn_Ctrl_GH_H4 <= GateSignals_out1_GH_H4;

  AmerIn_Ctrl_GH_H3 <= GateSignals_out1_GH_H3;

  AmerIn_Ctrl_GH_H2 <= GateSignals_out1_GH_H2;

  AmerIn_Ctrl_GH_H1 <= GateSignals_out1_GH_H1;

  AmerIn_Ctrl_GL_L4 <= GateSignals_out1_GL_L4;

  AmerIn_Ctrl_GL_L3 <= GateSignals_out1_GL_L3;

  AmerIn_Ctrl_GL_L2 <= GateSignals_out1_GL_L2;

  AmerIn_Ctrl_GL_L1 <= GateSignals_out1_GL_L1;

  AmerIn_SlowIn_IN7 <= IO_Extension_Inputs_out1_IN7;

  AmerIn_SlowIn_IN6 <= IO_Extension_Inputs_out1_IN6;

  AmerIn_SlowIn_IN5 <= IO_Extension_Inputs_out1_IN5;

  AmerIn_SlowIn_IN4 <= IO_Extension_Inputs_out1_IN4;

  AmerIn_SlowIn_IN3 <= IO_Extension_Inputs_out1_IN3;

  AmerIn_SlowIn_IN2 <= IO_Extension_Inputs_out1_IN2;

  AmerIn_SlowIn_IN1 <= IO_Extension_Inputs_out1_IN1;

  AmerIn_SlowIn_HILboardSW <= IO_Extension_Inputs_out1_HILboardSW;

END rtl;

