-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_IO_Extension_Inputs.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_IO_Extension_Inputs
-- Source Path: RLUb_HIL/AmerInputs/IO Extension Inputs
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_IO_Extension_Inputs IS
  PORT( In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        SlowIn_IN7                        :   OUT   std_logic;  -- ufix1
        SlowIn_IN6                        :   OUT   std_logic;  -- ufix1
        SlowIn_IN5                        :   OUT   std_logic;  -- ufix1
        SlowIn_IN4                        :   OUT   std_logic;  -- ufix1
        SlowIn_IN3                        :   OUT   std_logic;  -- ufix1
        SlowIn_IN2                        :   OUT   std_logic;  -- ufix1
        SlowIn_IN1                        :   OUT   std_logic;  -- ufix1
        SlowIn_HILboardSW                 :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_IO_Extension_Inputs;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_IO_Extension_Inputs IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL IN7                              : std_logic;  -- ufix1
  SIGNAL IN6                              : std_logic;  -- ufix1
  SIGNAL IN5                              : std_logic;  -- ufix1
  SIGNAL IN4                              : std_logic;  -- ufix1
  SIGNAL IN3                              : std_logic;  -- ufix1
  SIGNAL IN2                              : std_logic;  -- ufix1
  SIGNAL IN1_1                            : std_logic;  -- ufix1
  SIGNAL HILboardSW                       : std_logic;  -- ufix1

BEGIN
  In1_unsigned <= unsigned(In1);

  IN7 <= In1_unsigned(7);

  SlowIn_IN7 <= IN7;

  IN6 <= In1_unsigned(6);

  SlowIn_IN6 <= IN6;

  IN5 <= In1_unsigned(5);

  SlowIn_IN5 <= IN5;

  IN4 <= In1_unsigned(4);

  SlowIn_IN4 <= IN4;

  IN3 <= In1_unsigned(3);

  SlowIn_IN3 <= IN3;

  IN2 <= In1_unsigned(2);

  SlowIn_IN2 <= IN2;

  IN1_1 <= In1_unsigned(1);

  SlowIn_IN1 <= IN1_1;

  HILboardSW <= In1_unsigned(0);

  SlowIn_HILboardSW <= HILboardSW;

END rtl;

