# AMER_HIL


# Timing Specification Constraints


# FPGA Pin Location Constrain

set_property PACKAGE_PIN M14 [get_ports {ZyboLED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboLED[0]}]
set_property PACKAGE_PIN M15 [get_ports {ZyboLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboLED[1]}]
set_property PACKAGE_PIN G14 [get_ports {ZyboLED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboLED[2]}]
set_property PACKAGE_PIN D18 [get_ports {ZyboLED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboLED[3]}]
set_property PACKAGE_PIN P16 [get_ports {ZyboBTN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboBTN[0]}]
set_property PACKAGE_PIN V16 [get_ports {ZyboBTN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboBTN[1]}]
set_property PACKAGE_PIN Y16 [get_ports {ZyboBTN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboBTN[2]}]
set_property PACKAGE_PIN G15 [get_ports {ZyboSW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboSW[0]}]
set_property PACKAGE_PIN P15 [get_ports {ZyboSW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboSW[1]}]
set_property PACKAGE_PIN W13 [get_ports {ZyboSW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboSW[2]}]
set_property PACKAGE_PIN T16 [get_ports {ZyboSW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZyboSW[3]}]
set_property PACKAGE_PIN V12 [get_ports {CtrlH[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlH[0]}]
set_property PACKAGE_PIN W16 [get_ports {CtrlH[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlH[1]}]
set_property PACKAGE_PIN J15 [get_ports {CtrlH[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlH[2]}]
set_property PACKAGE_PIN H15 [get_ports {CtrlH[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlH[3]}]
set_property PACKAGE_PIN V13 [get_ports {CtrlL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlL[0]}]
set_property PACKAGE_PIN U17 [get_ports {CtrlL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlL[1]}]
set_property PACKAGE_PIN T17 [get_ports {CtrlL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlL[2]}]
set_property PACKAGE_PIN Y17 [get_ports {CtrlL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CtrlL[3]}]
set_property PACKAGE_PIN T15 [get_ports {Status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Status[0]}]
set_property PACKAGE_PIN R14 [get_ports {Status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Status[1]}]
set_property PACKAGE_PIN U15 [get_ports {Status[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Status[2]}]
set_property PACKAGE_PIN V18 [get_ports {Status[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Status[3]}]
set_property PACKAGE_PIN U20 [get_ports {Fail[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Fail[0]}]
set_property PACKAGE_PIN W20 [get_ports {Fail[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Fail[1]}]
set_property PACKAGE_PIN Y19 [get_ports {Fail[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Fail[2]}]
set_property PACKAGE_PIN W19 [get_ports {Fail[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Fail[3]}]
set_property PACKAGE_PIN T10 [get_ports {QEP[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QEP[0]}]
set_property PACKAGE_PIN T12 [get_ports {QEP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QEP[1]}]
set_property PACKAGE_PIN U12 [get_ports {QEP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QEP[2]}]
set_property PACKAGE_PIN T11 [get_ports {QEP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QEP[3]}]
