-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_dut.vhd
-- Created: 2026-03-27 14:58:46
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_dut
-- Source Path: RLUb_HIL_ip/RLUb_HIL_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        ZyboBTN                           :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        ZyboSW                            :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlH                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlL                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        IOextIn                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        ht_Param0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Param7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        ZyboLED                           :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        SD_MUX_A                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        SD_MUX_B                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        IOextOut                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        Status                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Fail                              :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        QEP                               :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        ht_Data0                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Data1                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Data2                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Data3                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ht_Data4                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END RLUb_HIL_ip_dut;


ARCHITECTURE rtl OF RLUb_HIL_ip_dut IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_RLUb_HIL
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          ZyboBTN                         :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          ZyboSW                          :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlH                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlL                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          IOextIn                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          ht_Param0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Param7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          ZyboLED                         :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          SD_MUX_A                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          SD_MUX_B                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          IOextOut                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          Status                          :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          Fail                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          QEP                             :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          ht_Data0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ht_Data4                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_RLUb_HIL
    USE ENTITY work.RLUb_HIL_ip_src_RLUb_HIL(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL ZyboLED_sig                      : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL SD_MUX_A_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL SD_MUX_B_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL IOextOut_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Status_sig                       : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL Fail_sig                         : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL QEP_sig                          : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL ht_Data0_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data1_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data2_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data3_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ht_Data4_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_RLUb_HIL_ip_src_RLUb_HIL : RLUb_HIL_ip_src_RLUb_HIL
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              ZyboBTN => ZyboBTN,  -- ufix3
              ZyboSW => ZyboSW,  -- ufix4
              CtrlH => CtrlH,  -- ufix4
              CtrlL => CtrlL,  -- ufix4
              IOextIn => IOextIn,  -- ufix8
              ht_Param0 => ht_Param0,  -- ufix32
              ht_Param1 => ht_Param1,  -- ufix32
              ht_Param2 => ht_Param2,  -- ufix32
              ht_Param3 => ht_Param3,  -- ufix32
              ht_Param4 => ht_Param4,  -- ufix32
              ht_Param5 => ht_Param5,  -- ufix32
              ht_Param6 => ht_Param6,  -- ufix32
              ht_Param7 => ht_Param7,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              ZyboLED => ZyboLED_sig,  -- ufix4
              SD_MUX_A => SD_MUX_A_sig,  -- ufix8
              SD_MUX_B => SD_MUX_B_sig,  -- ufix8
              IOextOut => IOextOut_sig,  -- ufix8
              Status => Status_sig,  -- ufix4
              Fail => Fail_sig,  -- ufix4
              QEP => QEP_sig,  -- ufix4
              ht_Data0 => ht_Data0_sig,  -- ufix32
              ht_Data1 => ht_Data1_sig,  -- ufix32
              ht_Data2 => ht_Data2_sig,  -- ufix32
              ht_Data3 => ht_Data3_sig,  -- ufix32
              ht_Data4 => ht_Data4_sig  -- ufix32
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  ZyboLED <= ZyboLED_sig;

  SD_MUX_A <= SD_MUX_A_sig;

  SD_MUX_B <= SD_MUX_B_sig;

  IOextOut <= IOextOut_sig;

  Status <= Status_sig;

  Fail <= Fail_sig;

  QEP <= QEP_sig;

  ht_Data0 <= ht_Data0_sig;

  ht_Data1 <= ht_Data1_sig;

  ht_Data2 <= ht_Data2_sig;

  ht_Data3 <= ht_Data3_sig;

  ht_Data4 <= ht_Data4_sig;

END rtl;

