-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_RLUb_HIL.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 5e-08
-- Target subsystem base rate: 5e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        5e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ZyboLED                       ce_out        5e-08
-- SD_MUX_A                      ce_out        5e-08
-- SD_MUX_B                      ce_out        5e-08
-- IOextOut                      ce_out        5e-08
-- Status                        ce_out        5e-08
-- Fail                          ce_out        5e-08
-- QEP                           ce_out        5e-08
-- ht_Data0                      ce_out        5e-08
-- ht_Data1                      ce_out        5e-08
-- ht_Data2                      ce_out        5e-08
-- ht_Data3                      ce_out        5e-08
-- ht_Data4                      ce_out        5e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_RLUb_HIL
-- Source Path: RLUb_HIL
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.RLUb_HIL_ip_src_RLUb_HIL_pkg.ALL;

ENTITY RLUb_HIL_ip_src_RLUb_HIL IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ZyboBTN                           :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        ZyboSW                            :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlH                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        CtrlL                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        IOextIn                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ht_Param0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Param7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        ZyboLED                           :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        SD_MUX_A                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        SD_MUX_B                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        IOextOut                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Status                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Fail                              :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        QEP                               :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        ht_Data0                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Data1                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Data2                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Data3                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        ht_Data4                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END RLUb_HIL_ip_src_RLUb_HIL;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_RLUb_HIL IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_AmerInputs
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          ZyboBTN                         :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          ZyboSW                          :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlH                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          CtrlL                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          IOextIn                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          AmerIn_ZyboBTN_BTN3             :   OUT   std_logic;  -- ufix1
          AmerIn_ZyboBTN_BTN2             :   OUT   std_logic;  -- ufix1
          AmerIn_ZyboBTN_BTN1             :   OUT   std_logic;  -- ufix1
          AmerIn_ZyboSW_SW3               :   OUT   std_logic;  -- ufix1
          AmerIn_ZyboSW_SW2               :   OUT   std_logic;  -- ufix1
          AmerIn_ZyboSW_SW1               :   OUT   std_logic;  -- ufix1
          AmerIn_ZyboSW_SW0               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H4               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H3               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H2               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H1               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L4               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L3               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L2               :   OUT   std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L1               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN7               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN6               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN5               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN4               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN3               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN2               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_IN1               :   OUT   std_logic;  -- ufix1
          AmerIn_SlowIn_HILboardSW        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_HitermInputs
    PORT( CntLimit                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          SlowOut                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Status                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Fail                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Encoder                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          LEDs                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Udc                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Ub                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Params_CntLimit                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          Params_SlowOut_OUT7             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_OUT6             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_OUT5             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_OUT4             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_OUT3             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_OUT2             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_OUT1             :   OUT   std_logic;  -- ufix1
          Params_SlowOut_HILboardRLED     :   OUT   std_logic;  -- ufix1
          Params_Status_Status4           :   OUT   std_logic;  -- ufix1
          Params_Status_Status3           :   OUT   std_logic;  -- ufix1
          Params_Status_Status2           :   OUT   std_logic;  -- ufix1
          Params_Status_Status1           :   OUT   std_logic;  -- ufix1
          Params_Fail_Fail4               :   OUT   std_logic;  -- ufix1
          Params_Fail_Fail3               :   OUT   std_logic;  -- ufix1
          Params_Fail_Fail2               :   OUT   std_logic;  -- ufix1
          Params_Fail_Fail1               :   OUT   std_logic;  -- ufix1
          Params_Encoder_I                :   OUT   std_logic;  -- ufix1
          Params_Encoder_Z                :   OUT   std_logic;  -- ufix1
          Params_Encoder_B                :   OUT   std_logic;  -- ufix1
          Params_Encoder_A                :   OUT   std_logic;  -- ufix1
          Params_LEDs                     :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          Params_Udc                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Params_Ub                       :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En16
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_RLUb_DTFX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          control_Inport_1_signal1_GH     :   IN    std_logic;
          control_Inport_1_signal1_GL     :   IN    std_logic;
          control_Inport_1_gate_en        :   IN    std_logic;
          par_Inport_2_Udc                :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          par_Inport_2_Ub                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          y_Outport_1_Iout                :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
          y_Outport_1_Vout                :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          y_Outport_1_Udc                 :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          y_Outport_1_Ub                  :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En16
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_SignalMUX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          ModelOut_Iout                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
          ModelOut_Vout                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          ModelOut_Udc                    :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          ModelOut_Ub                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Params_CntLimit                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Params_SlowOut_OUT7             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT6             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT5             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT4             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT3             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT2             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT1             :   IN    std_logic;  -- ufix1
          Params_SlowOut_HILboardRLED     :   IN    std_logic;  -- ufix1
          Params_Status_Status4           :   IN    std_logic;  -- ufix1
          Params_Status_Status3           :   IN    std_logic;  -- ufix1
          Params_Status_Status2           :   IN    std_logic;  -- ufix1
          Params_Status_Status1           :   IN    std_logic;  -- ufix1
          Params_Fail_Fail4               :   IN    std_logic;  -- ufix1
          Params_Fail_Fail3               :   IN    std_logic;  -- ufix1
          Params_Fail_Fail2               :   IN    std_logic;  -- ufix1
          Params_Fail_Fail1               :   IN    std_logic;  -- ufix1
          Params_Encoder_I                :   IN    std_logic;  -- ufix1
          Params_Encoder_Z                :   IN    std_logic;  -- ufix1
          Params_Encoder_B                :   IN    std_logic;  -- ufix1
          Params_Encoder_A                :   IN    std_logic;  -- ufix1
          Params_LEDs                     :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          Params_Udc                      :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Params_Ub                       :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          AmerOut_ANA_CH7                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH6                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH5                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH4                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH3                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH2                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH1                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH0                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH7                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH6                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH5                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH4                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH3                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH2                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH1                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH0                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_SlowOut_OUT7            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_OUT6            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_OUT5            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_OUT4            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_OUT3            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_OUT2            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_OUT1            :   OUT   std_logic;  -- ufix1
          AmerOut_SlowOut_HILboardRLED    :   OUT   std_logic;  -- ufix1
          AmerOut_Status_Status4          :   OUT   std_logic;  -- ufix1
          AmerOut_Status_Status3          :   OUT   std_logic;  -- ufix1
          AmerOut_Status_Status2          :   OUT   std_logic;  -- ufix1
          AmerOut_Status_Status1          :   OUT   std_logic;  -- ufix1
          AmerOut_Fail_Fail4              :   OUT   std_logic;  -- ufix1
          AmerOut_Fail_Fail3              :   OUT   std_logic;  -- ufix1
          AmerOut_Fail_Fail2              :   OUT   std_logic;  -- ufix1
          AmerOut_Fail_Fail1              :   OUT   std_logic;  -- ufix1
          AmerOut_Encoder_I               :   OUT   std_logic;  -- ufix1
          AmerOut_Encoder_Z               :   OUT   std_logic;  -- ufix1
          AmerOut_Encoder_B               :   OUT   std_logic;  -- ufix1
          AmerOut_Encoder_A               :   OUT   std_logic;  -- ufix1
          AmerOut_ZyboLED_LED3            :   OUT   std_logic;  -- ufix1
          AmerOut_ZyboLED_LED2            :   OUT   std_logic;  -- ufix1
          AmerOut_ZyboLED_LED1            :   OUT   std_logic;  -- ufix1
          AmerOut_ZyboLED_LED0            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_AmerOutputs
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AmerOut_ANA_CH7                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH6                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH5                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH4                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH3                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH2                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH1                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANA_CH0                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH7                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH6                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH5                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH4                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH3                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH2                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH1                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_ANB_CH0                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AmerOut_SlowOut_OUT7            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_OUT6            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_OUT5            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_OUT4            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_OUT3            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_OUT2            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_OUT1            :   IN    std_logic;  -- ufix1
          AmerOut_SlowOut_HILboardRLED    :   IN    std_logic;  -- ufix1
          AmerOut_Status_Status4          :   IN    std_logic;  -- ufix1
          AmerOut_Status_Status3          :   IN    std_logic;  -- ufix1
          AmerOut_Status_Status2          :   IN    std_logic;  -- ufix1
          AmerOut_Status_Status1          :   IN    std_logic;  -- ufix1
          AmerOut_Fail_Fail4              :   IN    std_logic;  -- ufix1
          AmerOut_Fail_Fail3              :   IN    std_logic;  -- ufix1
          AmerOut_Fail_Fail2              :   IN    std_logic;  -- ufix1
          AmerOut_Fail_Fail1              :   IN    std_logic;  -- ufix1
          AmerOut_Encoder_I               :   IN    std_logic;  -- ufix1
          AmerOut_Encoder_Z               :   IN    std_logic;  -- ufix1
          AmerOut_Encoder_B               :   IN    std_logic;  -- ufix1
          AmerOut_Encoder_A               :   IN    std_logic;  -- ufix1
          AmerOut_ZyboLED_LED3            :   IN    std_logic;  -- ufix1
          AmerOut_ZyboLED_LED2            :   IN    std_logic;  -- ufix1
          AmerOut_ZyboLED_LED1            :   IN    std_logic;  -- ufix1
          AmerOut_ZyboLED_LED0            :   IN    std_logic;  -- ufix1
          ZyboLED                         :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          SD_MUX_A                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          SD_MUX_B                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          IOextOut                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Status                          :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          Fail                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          QEP                             :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_HitermOutputs
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AmerIn_ZyboBTN_BTN3             :   IN    std_logic;  -- ufix1
          AmerIn_ZyboBTN_BTN2             :   IN    std_logic;  -- ufix1
          AmerIn_ZyboBTN_BTN1             :   IN    std_logic;  -- ufix1
          AmerIn_ZyboSW_SW3               :   IN    std_logic;  -- ufix1
          AmerIn_ZyboSW_SW2               :   IN    std_logic;  -- ufix1
          AmerIn_ZyboSW_SW1               :   IN    std_logic;  -- ufix1
          AmerIn_ZyboSW_SW0               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H4               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H3               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H2               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GH_H1               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L4               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L3               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L2               :   IN    std_logic;  -- ufix1
          AmerIn_Ctrl_GL_L1               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN7               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN6               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN5               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN4               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN3               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN2               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_IN1               :   IN    std_logic;  -- ufix1
          AmerIn_SlowIn_HILboardSW        :   IN    std_logic;  -- ufix1
          ModelOut_Iout                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
          ModelOut_Vout                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          ModelOut_Udc                    :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          ModelOut_Ub                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Params_CntLimit                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Params_SlowOut_OUT7             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT6             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT5             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT4             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT3             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT2             :   IN    std_logic;  -- ufix1
          Params_SlowOut_OUT1             :   IN    std_logic;  -- ufix1
          Params_SlowOut_HILboardRLED     :   IN    std_logic;  -- ufix1
          Params_Status_Status4           :   IN    std_logic;  -- ufix1
          Params_Status_Status3           :   IN    std_logic;  -- ufix1
          Params_Status_Status2           :   IN    std_logic;  -- ufix1
          Params_Status_Status1           :   IN    std_logic;  -- ufix1
          Params_Fail_Fail4               :   IN    std_logic;  -- ufix1
          Params_Fail_Fail3               :   IN    std_logic;  -- ufix1
          Params_Fail_Fail2               :   IN    std_logic;  -- ufix1
          Params_Fail_Fail1               :   IN    std_logic;  -- ufix1
          Params_Encoder_I                :   IN    std_logic;  -- ufix1
          Params_Encoder_Z                :   IN    std_logic;  -- ufix1
          Params_Encoder_B                :   IN    std_logic;  -- ufix1
          Params_Encoder_A                :   IN    std_logic;  -- ufix1
          Params_LEDs                     :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          Params_Udc                      :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Params_Ub                       :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          Cnt                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          SW                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          SlowIn                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Iout                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Vout                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_AmerInputs
    USE ENTITY work.RLUb_HIL_ip_src_AmerInputs(rtl);

  FOR ALL : RLUb_HIL_ip_src_HitermInputs
    USE ENTITY work.RLUb_HIL_ip_src_HitermInputs(rtl);

  FOR ALL : RLUb_HIL_ip_src_RLUb_DTFX
    USE ENTITY work.RLUb_HIL_ip_src_RLUb_DTFX(rtl);

  FOR ALL : RLUb_HIL_ip_src_SignalMUX
    USE ENTITY work.RLUb_HIL_ip_src_SignalMUX(rtl);

  FOR ALL : RLUb_HIL_ip_src_AmerOutputs
    USE ENTITY work.RLUb_HIL_ip_src_AmerOutputs(rtl);

  FOR ALL : RLUb_HIL_ip_src_HitermOutputs
    USE ENTITY work.RLUb_HIL_ip_src_HitermOutputs(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL AmerInputs_out1_ZyboBTN_BTN3     : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_ZyboBTN_BTN2     : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_ZyboBTN_BTN1     : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_ZyboSW_SW3       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_ZyboSW_SW2       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_ZyboSW_SW1       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_ZyboSW_SW0       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GH_H4       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GH_H3       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GH_H2       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GH_H1       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GL_L4       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GL_L3       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GL_L2       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_Ctrl_GL_L1       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN7       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN6       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN5       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN4       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN3       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN2       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_IN1       : std_logic;  -- ufix1
  SIGNAL AmerInputs_out1_SlowIn_HILboardSW : std_logic;  -- ufix1
  SIGNAL H1                               : std_logic;  -- ufix1
  SIGNAL GH                               : std_logic;
  SIGNAL L1                               : std_logic;  -- ufix1
  SIGNAL GL                               : std_logic;
  SIGNAL HitermInputs_out1_CntLimit       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HitermInputs_out1_SlowOut_OUT7   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_OUT6   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_OUT5   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_OUT4   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_OUT3   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_OUT2   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_OUT1   : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_SlowOut_HILboardRLED : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Status_Status4 : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Status_Status3 : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Status_Status2 : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Status_Status1 : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Fail_Fail4     : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Fail_Fail3     : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Fail_Fail2     : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Fail_Fail1     : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Encoder_I      : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Encoder_Z      : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Encoder_B      : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_Encoder_A      : std_logic;  -- ufix1
  SIGNAL HitermInputs_out1_LEDs           : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL HitermInputs_out1_Udc            : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL HitermInputs_out1_Ub             : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL gate_en                          : std_logic;
  SIGNAL Udc                              : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Ub                               : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL RLUb_DTFX_out1_Iout              : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL RLUb_DTFX_out1_Vout              : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL RLUb_DTFX_out1_Udc               : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL RLUb_DTFX_out1_Ub                : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL SignalMUX_out1_ANA_CH7           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH6           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH5           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH4           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH3           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH2           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH1           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANA_CH0           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH7           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH6           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH5           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH4           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH3           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH2           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH1           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_ANB_CH0           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SignalMUX_out1_SlowOut_OUT7      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_OUT6      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_OUT5      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_OUT4      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_OUT3      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_OUT2      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_OUT1      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_SlowOut_HILboardRLED : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Status_Status4    : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Status_Status3    : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Status_Status2    : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Status_Status1    : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Fail_Fail4        : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Fail_Fail3        : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Fail_Fail2        : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Fail_Fail1        : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Encoder_I         : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Encoder_Z         : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Encoder_B         : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_Encoder_A         : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_ZyboLED_LED3      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_ZyboLED_LED2      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_ZyboLED_LED1      : std_logic;  -- ufix1
  SIGNAL SignalMUX_out1_ZyboLED_LED0      : std_logic;  -- ufix1
  SIGNAL y                                : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL y_1                              : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL y_2                              : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL y_3                              : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL y_4                              : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL y_5                              : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL y_6                              : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL HitermOutputs_out1               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL HitermOutputs_out2               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL HitermOutputs_out3               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL HitermOutputs_out4               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL HitermOutputs_out5               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL HitermOutputs_out1_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL delayMatch_reg                   : vector_of_unsigned32(0 TO 1);  -- ufix32 [2]
  SIGNAL HitermOutputs_out1_1             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL HitermOutputs_out2_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL delayMatch1_reg                  : vector_of_unsigned32(0 TO 1);  -- ufix32 [2]
  SIGNAL HitermOutputs_out2_1             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL HitermOutputs_out3_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL delayMatch2_reg                  : vector_of_unsigned32(0 TO 1);  -- ufix32 [2]
  SIGNAL HitermOutputs_out3_1             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL HitermOutputs_out4_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL delayMatch3_reg                  : vector_of_unsigned32(0 TO 1);  -- ufix32 [2]
  SIGNAL HitermOutputs_out4_1             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL HitermOutputs_out5_unsigned      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL delayMatch4_reg                  : vector_of_unsigned32(0 TO 1);  -- ufix32 [2]
  SIGNAL HitermOutputs_out5_1             : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_AmerInputs : RLUb_HIL_ip_src_AmerInputs
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              ZyboBTN => ZyboBTN,  -- ufix3
              ZyboSW => ZyboSW,  -- ufix4
              CtrlH => CtrlH,  -- ufix4
              CtrlL => CtrlL,  -- ufix4
              IOextIn => IOextIn,  -- uint8
              AmerIn_ZyboBTN_BTN3 => AmerInputs_out1_ZyboBTN_BTN3,  -- ufix1
              AmerIn_ZyboBTN_BTN2 => AmerInputs_out1_ZyboBTN_BTN2,  -- ufix1
              AmerIn_ZyboBTN_BTN1 => AmerInputs_out1_ZyboBTN_BTN1,  -- ufix1
              AmerIn_ZyboSW_SW3 => AmerInputs_out1_ZyboSW_SW3,  -- ufix1
              AmerIn_ZyboSW_SW2 => AmerInputs_out1_ZyboSW_SW2,  -- ufix1
              AmerIn_ZyboSW_SW1 => AmerInputs_out1_ZyboSW_SW1,  -- ufix1
              AmerIn_ZyboSW_SW0 => AmerInputs_out1_ZyboSW_SW0,  -- ufix1
              AmerIn_Ctrl_GH_H4 => AmerInputs_out1_Ctrl_GH_H4,  -- ufix1
              AmerIn_Ctrl_GH_H3 => AmerInputs_out1_Ctrl_GH_H3,  -- ufix1
              AmerIn_Ctrl_GH_H2 => AmerInputs_out1_Ctrl_GH_H2,  -- ufix1
              AmerIn_Ctrl_GH_H1 => AmerInputs_out1_Ctrl_GH_H1,  -- ufix1
              AmerIn_Ctrl_GL_L4 => AmerInputs_out1_Ctrl_GL_L4,  -- ufix1
              AmerIn_Ctrl_GL_L3 => AmerInputs_out1_Ctrl_GL_L3,  -- ufix1
              AmerIn_Ctrl_GL_L2 => AmerInputs_out1_Ctrl_GL_L2,  -- ufix1
              AmerIn_Ctrl_GL_L1 => AmerInputs_out1_Ctrl_GL_L1,  -- ufix1
              AmerIn_SlowIn_IN7 => AmerInputs_out1_SlowIn_IN7,  -- ufix1
              AmerIn_SlowIn_IN6 => AmerInputs_out1_SlowIn_IN6,  -- ufix1
              AmerIn_SlowIn_IN5 => AmerInputs_out1_SlowIn_IN5,  -- ufix1
              AmerIn_SlowIn_IN4 => AmerInputs_out1_SlowIn_IN4,  -- ufix1
              AmerIn_SlowIn_IN3 => AmerInputs_out1_SlowIn_IN3,  -- ufix1
              AmerIn_SlowIn_IN2 => AmerInputs_out1_SlowIn_IN2,  -- ufix1
              AmerIn_SlowIn_IN1 => AmerInputs_out1_SlowIn_IN1,  -- ufix1
              AmerIn_SlowIn_HILboardSW => AmerInputs_out1_SlowIn_HILboardSW  -- ufix1
              );

  u_HitermInputs : RLUb_HIL_ip_src_HitermInputs
    PORT MAP( CntLimit => ht_Param0,  -- uint32
              SlowOut => ht_Param1,  -- uint32
              Status => ht_Param2,  -- uint32
              Fail => ht_Param3,  -- uint32
              Encoder => ht_Param4,  -- uint32
              LEDs => ht_Param5,  -- uint32
              Udc => ht_Param6,  -- uint32
              Ub => ht_Param7,  -- uint32
              Params_CntLimit => HitermInputs_out1_CntLimit,  -- uint16
              Params_SlowOut_OUT7 => HitermInputs_out1_SlowOut_OUT7,  -- ufix1
              Params_SlowOut_OUT6 => HitermInputs_out1_SlowOut_OUT6,  -- ufix1
              Params_SlowOut_OUT5 => HitermInputs_out1_SlowOut_OUT5,  -- ufix1
              Params_SlowOut_OUT4 => HitermInputs_out1_SlowOut_OUT4,  -- ufix1
              Params_SlowOut_OUT3 => HitermInputs_out1_SlowOut_OUT3,  -- ufix1
              Params_SlowOut_OUT2 => HitermInputs_out1_SlowOut_OUT2,  -- ufix1
              Params_SlowOut_OUT1 => HitermInputs_out1_SlowOut_OUT1,  -- ufix1
              Params_SlowOut_HILboardRLED => HitermInputs_out1_SlowOut_HILboardRLED,  -- ufix1
              Params_Status_Status4 => HitermInputs_out1_Status_Status4,  -- ufix1
              Params_Status_Status3 => HitermInputs_out1_Status_Status3,  -- ufix1
              Params_Status_Status2 => HitermInputs_out1_Status_Status2,  -- ufix1
              Params_Status_Status1 => HitermInputs_out1_Status_Status1,  -- ufix1
              Params_Fail_Fail4 => HitermInputs_out1_Fail_Fail4,  -- ufix1
              Params_Fail_Fail3 => HitermInputs_out1_Fail_Fail3,  -- ufix1
              Params_Fail_Fail2 => HitermInputs_out1_Fail_Fail2,  -- ufix1
              Params_Fail_Fail1 => HitermInputs_out1_Fail_Fail1,  -- ufix1
              Params_Encoder_I => HitermInputs_out1_Encoder_I,  -- ufix1
              Params_Encoder_Z => HitermInputs_out1_Encoder_Z,  -- ufix1
              Params_Encoder_B => HitermInputs_out1_Encoder_B,  -- ufix1
              Params_Encoder_A => HitermInputs_out1_Encoder_A,  -- ufix1
              Params_LEDs => HitermInputs_out1_LEDs,  -- ufix4
              Params_Udc => HitermInputs_out1_Udc,  -- sfix25_En16
              Params_Ub => HitermInputs_out1_Ub  -- sfix25_En16
              );

  u_RLUb_DTFX : RLUb_HIL_ip_src_RLUb_DTFX
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              control_Inport_1_signal1_GH => GH,
              control_Inport_1_signal1_GL => GL,
              control_Inport_1_gate_en => gate_en,
              par_Inport_2_Udc => std_logic_vector(Udc),  -- sfix25_En16
              par_Inport_2_Ub => std_logic_vector(Ub),  -- sfix25_En16
              y_Outport_1_Iout => RLUb_DTFX_out1_Iout,  -- sfix25_En17
              y_Outport_1_Vout => RLUb_DTFX_out1_Vout,  -- sfix25_En16
              y_Outport_1_Udc => RLUb_DTFX_out1_Udc,  -- sfix25_En16
              y_Outport_1_Ub => RLUb_DTFX_out1_Ub  -- sfix25_En16
              );

  u_SignalMUX : RLUb_HIL_ip_src_SignalMUX
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              ModelOut_Iout => RLUb_DTFX_out1_Iout,  -- sfix25_En17
              ModelOut_Vout => RLUb_DTFX_out1_Vout,  -- sfix25_En16
              ModelOut_Udc => RLUb_DTFX_out1_Udc,  -- sfix25_En16
              ModelOut_Ub => RLUb_DTFX_out1_Ub,  -- sfix25_En16
              Params_CntLimit => HitermInputs_out1_CntLimit,  -- uint16
              Params_SlowOut_OUT7 => HitermInputs_out1_SlowOut_OUT7,  -- ufix1
              Params_SlowOut_OUT6 => HitermInputs_out1_SlowOut_OUT6,  -- ufix1
              Params_SlowOut_OUT5 => HitermInputs_out1_SlowOut_OUT5,  -- ufix1
              Params_SlowOut_OUT4 => HitermInputs_out1_SlowOut_OUT4,  -- ufix1
              Params_SlowOut_OUT3 => HitermInputs_out1_SlowOut_OUT3,  -- ufix1
              Params_SlowOut_OUT2 => HitermInputs_out1_SlowOut_OUT2,  -- ufix1
              Params_SlowOut_OUT1 => HitermInputs_out1_SlowOut_OUT1,  -- ufix1
              Params_SlowOut_HILboardRLED => HitermInputs_out1_SlowOut_HILboardRLED,  -- ufix1
              Params_Status_Status4 => HitermInputs_out1_Status_Status4,  -- ufix1
              Params_Status_Status3 => HitermInputs_out1_Status_Status3,  -- ufix1
              Params_Status_Status2 => HitermInputs_out1_Status_Status2,  -- ufix1
              Params_Status_Status1 => HitermInputs_out1_Status_Status1,  -- ufix1
              Params_Fail_Fail4 => HitermInputs_out1_Fail_Fail4,  -- ufix1
              Params_Fail_Fail3 => HitermInputs_out1_Fail_Fail3,  -- ufix1
              Params_Fail_Fail2 => HitermInputs_out1_Fail_Fail2,  -- ufix1
              Params_Fail_Fail1 => HitermInputs_out1_Fail_Fail1,  -- ufix1
              Params_Encoder_I => HitermInputs_out1_Encoder_I,  -- ufix1
              Params_Encoder_Z => HitermInputs_out1_Encoder_Z,  -- ufix1
              Params_Encoder_B => HitermInputs_out1_Encoder_B,  -- ufix1
              Params_Encoder_A => HitermInputs_out1_Encoder_A,  -- ufix1
              Params_LEDs => HitermInputs_out1_LEDs,  -- ufix4
              Params_Udc => HitermInputs_out1_Udc,  -- sfix25_En16
              Params_Ub => HitermInputs_out1_Ub,  -- sfix25_En16
              AmerOut_ANA_CH7 => SignalMUX_out1_ANA_CH7,  -- uint16
              AmerOut_ANA_CH6 => SignalMUX_out1_ANA_CH6,  -- uint16
              AmerOut_ANA_CH5 => SignalMUX_out1_ANA_CH5,  -- uint16
              AmerOut_ANA_CH4 => SignalMUX_out1_ANA_CH4,  -- uint16
              AmerOut_ANA_CH3 => SignalMUX_out1_ANA_CH3,  -- uint16
              AmerOut_ANA_CH2 => SignalMUX_out1_ANA_CH2,  -- uint16
              AmerOut_ANA_CH1 => SignalMUX_out1_ANA_CH1,  -- uint16
              AmerOut_ANA_CH0 => SignalMUX_out1_ANA_CH0,  -- uint16
              AmerOut_ANB_CH7 => SignalMUX_out1_ANB_CH7,  -- uint16
              AmerOut_ANB_CH6 => SignalMUX_out1_ANB_CH6,  -- uint16
              AmerOut_ANB_CH5 => SignalMUX_out1_ANB_CH5,  -- uint16
              AmerOut_ANB_CH4 => SignalMUX_out1_ANB_CH4,  -- uint16
              AmerOut_ANB_CH3 => SignalMUX_out1_ANB_CH3,  -- uint16
              AmerOut_ANB_CH2 => SignalMUX_out1_ANB_CH2,  -- uint16
              AmerOut_ANB_CH1 => SignalMUX_out1_ANB_CH1,  -- uint16
              AmerOut_ANB_CH0 => SignalMUX_out1_ANB_CH0,  -- uint16
              AmerOut_SlowOut_OUT7 => SignalMUX_out1_SlowOut_OUT7,  -- ufix1
              AmerOut_SlowOut_OUT6 => SignalMUX_out1_SlowOut_OUT6,  -- ufix1
              AmerOut_SlowOut_OUT5 => SignalMUX_out1_SlowOut_OUT5,  -- ufix1
              AmerOut_SlowOut_OUT4 => SignalMUX_out1_SlowOut_OUT4,  -- ufix1
              AmerOut_SlowOut_OUT3 => SignalMUX_out1_SlowOut_OUT3,  -- ufix1
              AmerOut_SlowOut_OUT2 => SignalMUX_out1_SlowOut_OUT2,  -- ufix1
              AmerOut_SlowOut_OUT1 => SignalMUX_out1_SlowOut_OUT1,  -- ufix1
              AmerOut_SlowOut_HILboardRLED => SignalMUX_out1_SlowOut_HILboardRLED,  -- ufix1
              AmerOut_Status_Status4 => SignalMUX_out1_Status_Status4,  -- ufix1
              AmerOut_Status_Status3 => SignalMUX_out1_Status_Status3,  -- ufix1
              AmerOut_Status_Status2 => SignalMUX_out1_Status_Status2,  -- ufix1
              AmerOut_Status_Status1 => SignalMUX_out1_Status_Status1,  -- ufix1
              AmerOut_Fail_Fail4 => SignalMUX_out1_Fail_Fail4,  -- ufix1
              AmerOut_Fail_Fail3 => SignalMUX_out1_Fail_Fail3,  -- ufix1
              AmerOut_Fail_Fail2 => SignalMUX_out1_Fail_Fail2,  -- ufix1
              AmerOut_Fail_Fail1 => SignalMUX_out1_Fail_Fail1,  -- ufix1
              AmerOut_Encoder_I => SignalMUX_out1_Encoder_I,  -- ufix1
              AmerOut_Encoder_Z => SignalMUX_out1_Encoder_Z,  -- ufix1
              AmerOut_Encoder_B => SignalMUX_out1_Encoder_B,  -- ufix1
              AmerOut_Encoder_A => SignalMUX_out1_Encoder_A,  -- ufix1
              AmerOut_ZyboLED_LED3 => SignalMUX_out1_ZyboLED_LED3,  -- ufix1
              AmerOut_ZyboLED_LED2 => SignalMUX_out1_ZyboLED_LED2,  -- ufix1
              AmerOut_ZyboLED_LED1 => SignalMUX_out1_ZyboLED_LED1,  -- ufix1
              AmerOut_ZyboLED_LED0 => SignalMUX_out1_ZyboLED_LED0  -- ufix1
              );

  u_AmerOutputs : RLUb_HIL_ip_src_AmerOutputs
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              AmerOut_ANA_CH7 => SignalMUX_out1_ANA_CH7,  -- uint16
              AmerOut_ANA_CH6 => SignalMUX_out1_ANA_CH6,  -- uint16
              AmerOut_ANA_CH5 => SignalMUX_out1_ANA_CH5,  -- uint16
              AmerOut_ANA_CH4 => SignalMUX_out1_ANA_CH4,  -- uint16
              AmerOut_ANA_CH3 => SignalMUX_out1_ANA_CH3,  -- uint16
              AmerOut_ANA_CH2 => SignalMUX_out1_ANA_CH2,  -- uint16
              AmerOut_ANA_CH1 => SignalMUX_out1_ANA_CH1,  -- uint16
              AmerOut_ANA_CH0 => SignalMUX_out1_ANA_CH0,  -- uint16
              AmerOut_ANB_CH7 => SignalMUX_out1_ANB_CH7,  -- uint16
              AmerOut_ANB_CH6 => SignalMUX_out1_ANB_CH6,  -- uint16
              AmerOut_ANB_CH5 => SignalMUX_out1_ANB_CH5,  -- uint16
              AmerOut_ANB_CH4 => SignalMUX_out1_ANB_CH4,  -- uint16
              AmerOut_ANB_CH3 => SignalMUX_out1_ANB_CH3,  -- uint16
              AmerOut_ANB_CH2 => SignalMUX_out1_ANB_CH2,  -- uint16
              AmerOut_ANB_CH1 => SignalMUX_out1_ANB_CH1,  -- uint16
              AmerOut_ANB_CH0 => SignalMUX_out1_ANB_CH0,  -- uint16
              AmerOut_SlowOut_OUT7 => SignalMUX_out1_SlowOut_OUT7,  -- ufix1
              AmerOut_SlowOut_OUT6 => SignalMUX_out1_SlowOut_OUT6,  -- ufix1
              AmerOut_SlowOut_OUT5 => SignalMUX_out1_SlowOut_OUT5,  -- ufix1
              AmerOut_SlowOut_OUT4 => SignalMUX_out1_SlowOut_OUT4,  -- ufix1
              AmerOut_SlowOut_OUT3 => SignalMUX_out1_SlowOut_OUT3,  -- ufix1
              AmerOut_SlowOut_OUT2 => SignalMUX_out1_SlowOut_OUT2,  -- ufix1
              AmerOut_SlowOut_OUT1 => SignalMUX_out1_SlowOut_OUT1,  -- ufix1
              AmerOut_SlowOut_HILboardRLED => SignalMUX_out1_SlowOut_HILboardRLED,  -- ufix1
              AmerOut_Status_Status4 => SignalMUX_out1_Status_Status4,  -- ufix1
              AmerOut_Status_Status3 => SignalMUX_out1_Status_Status3,  -- ufix1
              AmerOut_Status_Status2 => SignalMUX_out1_Status_Status2,  -- ufix1
              AmerOut_Status_Status1 => SignalMUX_out1_Status_Status1,  -- ufix1
              AmerOut_Fail_Fail4 => SignalMUX_out1_Fail_Fail4,  -- ufix1
              AmerOut_Fail_Fail3 => SignalMUX_out1_Fail_Fail3,  -- ufix1
              AmerOut_Fail_Fail2 => SignalMUX_out1_Fail_Fail2,  -- ufix1
              AmerOut_Fail_Fail1 => SignalMUX_out1_Fail_Fail1,  -- ufix1
              AmerOut_Encoder_I => SignalMUX_out1_Encoder_I,  -- ufix1
              AmerOut_Encoder_Z => SignalMUX_out1_Encoder_Z,  -- ufix1
              AmerOut_Encoder_B => SignalMUX_out1_Encoder_B,  -- ufix1
              AmerOut_Encoder_A => SignalMUX_out1_Encoder_A,  -- ufix1
              AmerOut_ZyboLED_LED3 => SignalMUX_out1_ZyboLED_LED3,  -- ufix1
              AmerOut_ZyboLED_LED2 => SignalMUX_out1_ZyboLED_LED2,  -- ufix1
              AmerOut_ZyboLED_LED1 => SignalMUX_out1_ZyboLED_LED1,  -- ufix1
              AmerOut_ZyboLED_LED0 => SignalMUX_out1_ZyboLED_LED0,  -- ufix1
              ZyboLED => y,  -- ufix4
              SD_MUX_A => y_1,  -- uint8
              SD_MUX_B => y_2,  -- uint8
              IOextOut => y_3,  -- uint8
              Status => y_4,  -- ufix4
              Fail => y_5,  -- ufix4
              QEP => y_6  -- ufix4
              );

  u_HitermOutputs : RLUb_HIL_ip_src_HitermOutputs
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              AmerIn_ZyboBTN_BTN3 => AmerInputs_out1_ZyboBTN_BTN3,  -- ufix1
              AmerIn_ZyboBTN_BTN2 => AmerInputs_out1_ZyboBTN_BTN2,  -- ufix1
              AmerIn_ZyboBTN_BTN1 => AmerInputs_out1_ZyboBTN_BTN1,  -- ufix1
              AmerIn_ZyboSW_SW3 => AmerInputs_out1_ZyboSW_SW3,  -- ufix1
              AmerIn_ZyboSW_SW2 => AmerInputs_out1_ZyboSW_SW2,  -- ufix1
              AmerIn_ZyboSW_SW1 => AmerInputs_out1_ZyboSW_SW1,  -- ufix1
              AmerIn_ZyboSW_SW0 => AmerInputs_out1_ZyboSW_SW0,  -- ufix1
              AmerIn_Ctrl_GH_H4 => AmerInputs_out1_Ctrl_GH_H4,  -- ufix1
              AmerIn_Ctrl_GH_H3 => AmerInputs_out1_Ctrl_GH_H3,  -- ufix1
              AmerIn_Ctrl_GH_H2 => AmerInputs_out1_Ctrl_GH_H2,  -- ufix1
              AmerIn_Ctrl_GH_H1 => AmerInputs_out1_Ctrl_GH_H1,  -- ufix1
              AmerIn_Ctrl_GL_L4 => AmerInputs_out1_Ctrl_GL_L4,  -- ufix1
              AmerIn_Ctrl_GL_L3 => AmerInputs_out1_Ctrl_GL_L3,  -- ufix1
              AmerIn_Ctrl_GL_L2 => AmerInputs_out1_Ctrl_GL_L2,  -- ufix1
              AmerIn_Ctrl_GL_L1 => AmerInputs_out1_Ctrl_GL_L1,  -- ufix1
              AmerIn_SlowIn_IN7 => AmerInputs_out1_SlowIn_IN7,  -- ufix1
              AmerIn_SlowIn_IN6 => AmerInputs_out1_SlowIn_IN6,  -- ufix1
              AmerIn_SlowIn_IN5 => AmerInputs_out1_SlowIn_IN5,  -- ufix1
              AmerIn_SlowIn_IN4 => AmerInputs_out1_SlowIn_IN4,  -- ufix1
              AmerIn_SlowIn_IN3 => AmerInputs_out1_SlowIn_IN3,  -- ufix1
              AmerIn_SlowIn_IN2 => AmerInputs_out1_SlowIn_IN2,  -- ufix1
              AmerIn_SlowIn_IN1 => AmerInputs_out1_SlowIn_IN1,  -- ufix1
              AmerIn_SlowIn_HILboardSW => AmerInputs_out1_SlowIn_HILboardSW,  -- ufix1
              ModelOut_Iout => RLUb_DTFX_out1_Iout,  -- sfix25_En17
              ModelOut_Vout => RLUb_DTFX_out1_Vout,  -- sfix25_En16
              ModelOut_Udc => RLUb_DTFX_out1_Udc,  -- sfix25_En16
              ModelOut_Ub => RLUb_DTFX_out1_Ub,  -- sfix25_En16
              Params_CntLimit => HitermInputs_out1_CntLimit,  -- uint16
              Params_SlowOut_OUT7 => HitermInputs_out1_SlowOut_OUT7,  -- ufix1
              Params_SlowOut_OUT6 => HitermInputs_out1_SlowOut_OUT6,  -- ufix1
              Params_SlowOut_OUT5 => HitermInputs_out1_SlowOut_OUT5,  -- ufix1
              Params_SlowOut_OUT4 => HitermInputs_out1_SlowOut_OUT4,  -- ufix1
              Params_SlowOut_OUT3 => HitermInputs_out1_SlowOut_OUT3,  -- ufix1
              Params_SlowOut_OUT2 => HitermInputs_out1_SlowOut_OUT2,  -- ufix1
              Params_SlowOut_OUT1 => HitermInputs_out1_SlowOut_OUT1,  -- ufix1
              Params_SlowOut_HILboardRLED => HitermInputs_out1_SlowOut_HILboardRLED,  -- ufix1
              Params_Status_Status4 => HitermInputs_out1_Status_Status4,  -- ufix1
              Params_Status_Status3 => HitermInputs_out1_Status_Status3,  -- ufix1
              Params_Status_Status2 => HitermInputs_out1_Status_Status2,  -- ufix1
              Params_Status_Status1 => HitermInputs_out1_Status_Status1,  -- ufix1
              Params_Fail_Fail4 => HitermInputs_out1_Fail_Fail4,  -- ufix1
              Params_Fail_Fail3 => HitermInputs_out1_Fail_Fail3,  -- ufix1
              Params_Fail_Fail2 => HitermInputs_out1_Fail_Fail2,  -- ufix1
              Params_Fail_Fail1 => HitermInputs_out1_Fail_Fail1,  -- ufix1
              Params_Encoder_I => HitermInputs_out1_Encoder_I,  -- ufix1
              Params_Encoder_Z => HitermInputs_out1_Encoder_Z,  -- ufix1
              Params_Encoder_B => HitermInputs_out1_Encoder_B,  -- ufix1
              Params_Encoder_A => HitermInputs_out1_Encoder_A,  -- ufix1
              Params_LEDs => HitermInputs_out1_LEDs,  -- ufix4
              Params_Udc => HitermInputs_out1_Udc,  -- sfix25_En16
              Params_Ub => HitermInputs_out1_Ub,  -- sfix25_En16
              Cnt => HitermOutputs_out1,  -- uint32
              SW => HitermOutputs_out2,  -- uint32
              SlowIn => HitermOutputs_out3,  -- uint32
              Iout => HitermOutputs_out4,  -- uint32
              Vout => HitermOutputs_out5  -- uint32
              );

  H1 <= AmerInputs_out1_Ctrl_GH_H1;

  
  GH <= '1' WHEN H1 /= '0' ELSE
      '0';

  L1 <= AmerInputs_out1_Ctrl_GL_L1;

  
  GL <= '1' WHEN L1 /= '0' ELSE
      '0';

  
  gate_en <= '1' WHEN AmerInputs_out1_SlowIn_IN1 /= '0' ELSE
      '0';

  Udc <= signed(HitermInputs_out1_Udc);

  Ub <= signed(HitermInputs_out1_Ub);

  HitermOutputs_out1_unsigned <= unsigned(HitermOutputs_out1);

  enb <= clk_enable;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_unsigned(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= HitermOutputs_out1_unsigned;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  HitermOutputs_out1_1 <= delayMatch_reg(1);

  ht_Data0 <= std_logic_vector(HitermOutputs_out1_1);

  HitermOutputs_out2_unsigned <= unsigned(HitermOutputs_out2);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => to_unsigned(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch1_reg(0) <= HitermOutputs_out2_unsigned;
        delayMatch1_reg(1) <= delayMatch1_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  HitermOutputs_out2_1 <= delayMatch1_reg(1);

  ht_Data1 <= std_logic_vector(HitermOutputs_out2_1);

  HitermOutputs_out3_unsigned <= unsigned(HitermOutputs_out3);

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch2_reg <= (OTHERS => to_unsigned(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch2_reg(0) <= HitermOutputs_out3_unsigned;
        delayMatch2_reg(1) <= delayMatch2_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch2_process;

  HitermOutputs_out3_1 <= delayMatch2_reg(1);

  ht_Data2 <= std_logic_vector(HitermOutputs_out3_1);

  HitermOutputs_out4_unsigned <= unsigned(HitermOutputs_out4);

  delayMatch3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch3_reg <= (OTHERS => to_unsigned(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch3_reg(0) <= HitermOutputs_out4_unsigned;
        delayMatch3_reg(1) <= delayMatch3_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch3_process;

  HitermOutputs_out4_1 <= delayMatch3_reg(1);

  ht_Data3 <= std_logic_vector(HitermOutputs_out4_1);

  HitermOutputs_out5_unsigned <= unsigned(HitermOutputs_out5);

  delayMatch4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch4_reg <= (OTHERS => to_unsigned(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch4_reg(0) <= HitermOutputs_out5_unsigned;
        delayMatch4_reg(1) <= delayMatch4_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch4_process;

  HitermOutputs_out5_1 <= delayMatch4_reg(1);

  ht_Data4 <= std_logic_vector(HitermOutputs_out5_1);

  ce_out <= clk_enable;

  ZyboLED <= y;

  SD_MUX_A <= y_1;

  SD_MUX_B <= y_2;

  IOextOut <= y_3;

  Status <= y_4;

  Fail <= y_5;

  QEP <= y_6;

END rtl;

