-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_AmerOutputs.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_AmerOutputs
-- Source Path: RLUb_HIL/AmerOutputs
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.RLUb_HIL_ip_src_RLUb_HIL_pkg.ALL;

ENTITY RLUb_HIL_ip_src_AmerOutputs IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AmerOut_ANA_CH7                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH6                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH5                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH4                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH3                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH2                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH1                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH0                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH7                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH6                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH5                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH4                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH3                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH2                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH1                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH0                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_SlowOut_OUT7              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_OUT6              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_OUT5              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_OUT4              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_OUT3              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_OUT2              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_OUT1              :   IN    std_logic;  -- ufix1
        AmerOut_SlowOut_HILboardRLED      :   IN    std_logic;  -- ufix1
        AmerOut_Status_Status4            :   IN    std_logic;  -- ufix1
        AmerOut_Status_Status3            :   IN    std_logic;  -- ufix1
        AmerOut_Status_Status2            :   IN    std_logic;  -- ufix1
        AmerOut_Status_Status1            :   IN    std_logic;  -- ufix1
        AmerOut_Fail_Fail4                :   IN    std_logic;  -- ufix1
        AmerOut_Fail_Fail3                :   IN    std_logic;  -- ufix1
        AmerOut_Fail_Fail2                :   IN    std_logic;  -- ufix1
        AmerOut_Fail_Fail1                :   IN    std_logic;  -- ufix1
        AmerOut_Encoder_I                 :   IN    std_logic;  -- ufix1
        AmerOut_Encoder_Z                 :   IN    std_logic;  -- ufix1
        AmerOut_Encoder_B                 :   IN    std_logic;  -- ufix1
        AmerOut_Encoder_A                 :   IN    std_logic;  -- ufix1
        AmerOut_ZyboLED_LED3              :   IN    std_logic;  -- ufix1
        AmerOut_ZyboLED_LED2              :   IN    std_logic;  -- ufix1
        AmerOut_ZyboLED_LED1              :   IN    std_logic;  -- ufix1
        AmerOut_ZyboLED_LED0              :   IN    std_logic;  -- ufix1
        ZyboLED                           :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        SD_MUX_A                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        SD_MUX_B                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        IOextOut                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Status                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Fail                              :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        QEP                               :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
        );
END RLUb_HIL_ip_src_AmerOutputs;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_AmerOutputs IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_Sigma_Delta
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          value                           :   IN    vector_of_std_logic_vector16(0 TO 15);  -- uint16 [16]
          out_rsvd                        :   OUT   std_logic_vector(0 TO 15)  -- boolean [16]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_Sigma_Delta
    USE ENTITY work.RLUb_HIL_ip_src_Sigma_Delta(rtl);

  -- Signals
  SIGNAL Bus_to_Vector4_out1              : std_logic_vector(0 TO 3);  -- ufix1 [4]
  SIGNAL Bit_Concat3_out1                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Mux_out1                         : vector_of_std_logic_vector16(0 TO 15);  -- ufix16 [16]
  SIGNAL Sigma_Delta_out1                 : std_logic_vector(0 TO 15);  -- boolean [16]
  SIGNAL Demux_out1                       : std_logic_vector(0 TO 7);  -- boolean [8]
  SIGNAL Bit_Concat6_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Demux_out2                       : std_logic_vector(0 TO 7);  -- boolean [8]
  SIGNAL Bit_Concat7_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bus_to_Vector3_out1              : std_logic_vector(0 TO 7);  -- ufix1 [8]
  SIGNAL Bit_Concat2_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bus_to_Vector_out1               : std_logic_vector(0 TO 3);  -- ufix1 [4]
  SIGNAL Bit_Concat4_out1                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bus_to_Vector1_out1              : std_logic_vector(0 TO 3);  -- ufix1 [4]
  SIGNAL Bit_Concat5_out1                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bus_to_Vector2_out1              : std_logic_vector(0 TO 3);  -- ufix1 [4]
  SIGNAL Bit_Concat1_out1                 : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  u_Sigma_Delta : RLUb_HIL_ip_src_Sigma_Delta
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              value => Mux_out1,  -- uint16 [16]
              out_rsvd => Sigma_Delta_out1  -- boolean [16]
              );

  Bus_to_Vector4_out1(0) <= AmerOut_ZyboLED_LED3;
  Bus_to_Vector4_out1(1) <= AmerOut_ZyboLED_LED2;
  Bus_to_Vector4_out1(2) <= AmerOut_ZyboLED_LED1;
  Bus_to_Vector4_out1(3) <= AmerOut_ZyboLED_LED0;

  Bit_Concat3_out1 <= unsigned'(Bus_to_Vector4_out1(0) & Bus_to_Vector4_out1(1) & Bus_to_Vector4_out1(2) & Bus_to_Vector4_out1(3));

  ZyboLED <= std_logic_vector(Bit_Concat3_out1);

  Mux_out1(0) <= AmerOut_ANA_CH7;
  Mux_out1(1) <= AmerOut_ANA_CH6;
  Mux_out1(2) <= AmerOut_ANA_CH5;
  Mux_out1(3) <= AmerOut_ANA_CH4;
  Mux_out1(4) <= AmerOut_ANA_CH3;
  Mux_out1(5) <= AmerOut_ANA_CH2;
  Mux_out1(6) <= AmerOut_ANA_CH1;
  Mux_out1(7) <= AmerOut_ANA_CH0;
  Mux_out1(8) <= AmerOut_ANB_CH7;
  Mux_out1(9) <= AmerOut_ANB_CH6;
  Mux_out1(10) <= AmerOut_ANB_CH5;
  Mux_out1(11) <= AmerOut_ANB_CH4;
  Mux_out1(12) <= AmerOut_ANB_CH3;
  Mux_out1(13) <= AmerOut_ANB_CH2;
  Mux_out1(14) <= AmerOut_ANB_CH1;
  Mux_out1(15) <= AmerOut_ANB_CH0;

  Demux_out1(0) <= Sigma_Delta_out1(0);
  Demux_out1(1) <= Sigma_Delta_out1(1);
  Demux_out1(2) <= Sigma_Delta_out1(2);
  Demux_out1(3) <= Sigma_Delta_out1(3);
  Demux_out1(4) <= Sigma_Delta_out1(4);
  Demux_out1(5) <= Sigma_Delta_out1(5);
  Demux_out1(6) <= Sigma_Delta_out1(6);
  Demux_out1(7) <= Sigma_Delta_out1(7);

  Bit_Concat6_out1 <= unsigned'(Demux_out1(0) & Demux_out1(1) & Demux_out1(2) & Demux_out1(3) & Demux_out1(4) & Demux_out1(5) & Demux_out1(6) & Demux_out1(7));

  SD_MUX_A <= std_logic_vector(Bit_Concat6_out1);

  Demux_out2(0) <= Sigma_Delta_out1(8);
  Demux_out2(1) <= Sigma_Delta_out1(9);
  Demux_out2(2) <= Sigma_Delta_out1(10);
  Demux_out2(3) <= Sigma_Delta_out1(11);
  Demux_out2(4) <= Sigma_Delta_out1(12);
  Demux_out2(5) <= Sigma_Delta_out1(13);
  Demux_out2(6) <= Sigma_Delta_out1(14);
  Demux_out2(7) <= Sigma_Delta_out1(15);

  Bit_Concat7_out1 <= unsigned'(Demux_out2(0) & Demux_out2(1) & Demux_out2(2) & Demux_out2(3) & Demux_out2(4) & Demux_out2(5) & Demux_out2(6) & Demux_out2(7));

  SD_MUX_B <= std_logic_vector(Bit_Concat7_out1);

  Bus_to_Vector3_out1(0) <= AmerOut_SlowOut_OUT7;
  Bus_to_Vector3_out1(1) <= AmerOut_SlowOut_OUT6;
  Bus_to_Vector3_out1(2) <= AmerOut_SlowOut_OUT5;
  Bus_to_Vector3_out1(3) <= AmerOut_SlowOut_OUT4;
  Bus_to_Vector3_out1(4) <= AmerOut_SlowOut_OUT3;
  Bus_to_Vector3_out1(5) <= AmerOut_SlowOut_OUT2;
  Bus_to_Vector3_out1(6) <= AmerOut_SlowOut_OUT1;
  Bus_to_Vector3_out1(7) <= AmerOut_SlowOut_HILboardRLED;

  Bit_Concat2_out1 <= unsigned'(Bus_to_Vector3_out1(0) & Bus_to_Vector3_out1(1) & Bus_to_Vector3_out1(2) & Bus_to_Vector3_out1(3) & Bus_to_Vector3_out1(4) & Bus_to_Vector3_out1(5) & Bus_to_Vector3_out1(6) & Bus_to_Vector3_out1(7));

  IOextOut <= std_logic_vector(Bit_Concat2_out1);

  Bus_to_Vector_out1(0) <= AmerOut_Status_Status4;
  Bus_to_Vector_out1(1) <= AmerOut_Status_Status3;
  Bus_to_Vector_out1(2) <= AmerOut_Status_Status2;
  Bus_to_Vector_out1(3) <= AmerOut_Status_Status1;

  Bit_Concat4_out1 <= unsigned'(Bus_to_Vector_out1(0) & Bus_to_Vector_out1(1) & Bus_to_Vector_out1(2) & Bus_to_Vector_out1(3));

  Status <= std_logic_vector(Bit_Concat4_out1);

  Bus_to_Vector1_out1(0) <= AmerOut_Fail_Fail4;
  Bus_to_Vector1_out1(1) <= AmerOut_Fail_Fail3;
  Bus_to_Vector1_out1(2) <= AmerOut_Fail_Fail2;
  Bus_to_Vector1_out1(3) <= AmerOut_Fail_Fail1;

  Bit_Concat5_out1 <= unsigned'(Bus_to_Vector1_out1(0) & Bus_to_Vector1_out1(1) & Bus_to_Vector1_out1(2) & Bus_to_Vector1_out1(3));

  Fail <= std_logic_vector(Bit_Concat5_out1);

  Bus_to_Vector2_out1(0) <= AmerOut_Encoder_I;
  Bus_to_Vector2_out1(1) <= AmerOut_Encoder_Z;
  Bus_to_Vector2_out1(2) <= AmerOut_Encoder_B;
  Bus_to_Vector2_out1(3) <= AmerOut_Encoder_A;

  Bit_Concat1_out1 <= unsigned'(Bus_to_Vector2_out1(0) & Bus_to_Vector2_out1(1) & Bus_to_Vector2_out1(2) & Bus_to_Vector2_out1(3));

  QEP <= std_logic_vector(Bit_Concat1_out1);

END rtl;

