# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Q:/work/hdl_prj/vivado_ip_prj/amer_top_constraint.xdc

# XDC: Q:/work/hdl_prj/vivado_ip_prj/RLUb_HIL_ip_src_RLUb_HIL_top.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ioexp_0_0/design_1_ioexp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ioexp_0_0 || ORIG_REF_NAME==design_1_ioexp_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mon_module_0_0/design_1_mon_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mon_module_0_0 || ORIG_REF_NAME==design_1_mon_module_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mon_module_0_0/hiterm.srcs/sources_1/ip/uart_cmd_RAM/uart_cmd_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_cmd_RAM || ORIG_REF_NAME==uart_cmd_RAM} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mon_module_0_0/hiterm.srcs/sources_1/ip/bbx_RAM/bbx_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bbx_RAM || ORIG_REF_NAME==bbx_RAM} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mon_module_0_0/hiterm.srcs/sources_1/ip/monitor_RAM/monitor_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==monitor_RAM || ORIG_REF_NAME==monitor_RAM} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sd_multiplexer_0_0/design_1_sd_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sd_multiplexer_0_0 || ORIG_REF_NAME==design_1_sd_multiplexer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RLUb_HIL_ip_0_0/design_1_RLUb_HIL_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RLUb_HIL_ip_0_0 || ORIG_REF_NAME==design_1_RLUb_HIL_ip_0_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_mon_module_0_0/hiterm.srcs/sources_1/ip/uart_cmd_RAM/uart_cmd_RAM_ooc.xdc

# XDC: bd/design_1/ip/design_1_mon_module_0_0/hiterm.srcs/sources_1/ip/bbx_RAM/bbx_RAM_ooc.xdc

# XDC: bd/design_1/ip/design_1_mon_module_0_0/hiterm.srcs/sources_1/ip/monitor_RAM/monitor_RAM_ooc.xdc

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
