function hB = plugin_board()
% Board definition
% Construct board object
hB = hdlcoder.Board;
hB.BoardName    = 'AMER_HIL';
% FPGA device information
hB.FPGAVendor   = 'Xilinx';
hB.FPGAFamily   = 'Zynq';
hB.FPGADevice   = 'xc7z010';
hB.FPGAPackage  = 'clg400';
hB.FPGASpeed    = '-1';
% Tool information
hB.SupportedTool = {'Xilinx Vivado'};
% FPGA JTAG chain position
hB.JTAGChainPosition = 2;
%% Add interfaces
% Standard "External Port" interface
hB.addExternalPortInterface( ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});
% Custom board external I/O interface
hB.addExternalIOInterface( ...
  'InterfaceID',    'Zybo user LED', ...
  'InterfaceType',  'OUT', ...
  'PortName',       'ZyboLED', ...
  'PortWidth',      4, ...
  'FPGAPin',        {'M14', 'M15', 'G14', 'D18'}, ...
  'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
   'InterfaceID',    'Zybo push buttons', ...
   'InterfaceType',  'IN', ...
   'PortName',       'ZyboBTN', ...
   'PortWidth',      3, ...
   'FPGAPin',        {'P16', 'V16', 'Y16'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
	'InterfaceID',    'Zybo slide switches', ...
	'InterfaceType',  'IN', ...
	'PortName',       'ZyboSW', ...
	'PortWidth',      4, ...
	'FPGAPin',        {'G15', 'P15', 'W13', 'T16'}, ...
	'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
	'InterfaceID',    'PWM signals (High side) ', ...
	'InterfaceType',  'INOUT', ...
	'PortName',       'CtrlH', ...
	'PortWidth',      4, ...
	'FPGAPin',        {'V12', 'W16', 'J15', 'H15'}, ...
	'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
	'InterfaceID',    'PWM signals (Low side) ', ...
	'InterfaceType',  'INOUT', ...
	'PortName',       'CtrlL', ...
	'PortWidth',      4, ...
	'FPGAPin',        {'V13', 'U17', 'T17', 'Y17'}, ...
	'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
	'InterfaceID',    'Status ', ...
	'InterfaceType',  'INOUT', ...
	'PortName',       'Status', ...
	'PortWidth',      4, ...
	'FPGAPin',        {'T15', 'R14', 'U15', 'V18'}, ...
	'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
	'InterfaceID',    'Fail ', ...
	'InterfaceType',  'INOUT', ...
	'PortName',       'Fail', ...
	'PortWidth',      4, ...
	'FPGAPin',        {'U20', 'W20', 'Y19', 'W19'}, ...
	'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

hB.addExternalIOInterface( ...
	'InterfaceID',    'Encoder (A, B, Z, I) ', ...
	'InterfaceType',  'INOUT', ...
	'PortName',       'QEP', ...
	'PortWidth',      4, ...
	'FPGAPin',        {'T10', 'T12', 'U12', 'T11'}, ...
	'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});


