-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_HitermInputs.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_HitermInputs
-- Source Path: RLUb_HIL/HitermInputs
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_HitermInputs IS
  PORT( CntLimit                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        SlowOut                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Status                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Fail                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Encoder                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        LEDs                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Udc                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Ub                                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Params_CntLimit                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        Params_SlowOut_OUT7               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_OUT6               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_OUT5               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_OUT4               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_OUT3               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_OUT2               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_OUT1               :   OUT   std_logic;  -- ufix1
        Params_SlowOut_HILboardRLED       :   OUT   std_logic;  -- ufix1
        Params_Status_Status4             :   OUT   std_logic;  -- ufix1
        Params_Status_Status3             :   OUT   std_logic;  -- ufix1
        Params_Status_Status2             :   OUT   std_logic;  -- ufix1
        Params_Status_Status1             :   OUT   std_logic;  -- ufix1
        Params_Fail_Fail4                 :   OUT   std_logic;  -- ufix1
        Params_Fail_Fail3                 :   OUT   std_logic;  -- ufix1
        Params_Fail_Fail2                 :   OUT   std_logic;  -- ufix1
        Params_Fail_Fail1                 :   OUT   std_logic;  -- ufix1
        Params_Encoder_I                  :   OUT   std_logic;  -- ufix1
        Params_Encoder_Z                  :   OUT   std_logic;  -- ufix1
        Params_Encoder_B                  :   OUT   std_logic;  -- ufix1
        Params_Encoder_A                  :   OUT   std_logic;  -- ufix1
        Params_LEDs                       :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Params_Udc                        :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        Params_Ub                         :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En16
        );
END RLUb_HIL_ip_src_HitermInputs;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_HitermInputs IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_Subsystem1
    PORT( Vio                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          SlowOut_OUT7                    :   OUT   std_logic;  -- ufix1
          SlowOut_OUT6                    :   OUT   std_logic;  -- ufix1
          SlowOut_OUT5                    :   OUT   std_logic;  -- ufix1
          SlowOut_OUT4                    :   OUT   std_logic;  -- ufix1
          SlowOut_OUT3                    :   OUT   std_logic;  -- ufix1
          SlowOut_OUT2                    :   OUT   std_logic;  -- ufix1
          SlowOut_OUT1                    :   OUT   std_logic;  -- ufix1
          SlowOut_HILboardRLED            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_Subsystem2
    PORT( Vio                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Status_Status4                  :   OUT   std_logic;  -- ufix1
          Status_Status3                  :   OUT   std_logic;  -- ufix1
          Status_Status2                  :   OUT   std_logic;  -- ufix1
          Status_Status1                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_Subsystem3
    PORT( Vio                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Fail_Fail4                      :   OUT   std_logic;  -- ufix1
          Fail_Fail3                      :   OUT   std_logic;  -- ufix1
          Fail_Fail2                      :   OUT   std_logic;  -- ufix1
          Fail_Fail1                      :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_Subsystem4
    PORT( Vio                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Encoder_I                       :   OUT   std_logic;  -- ufix1
          Encoder_Z                       :   OUT   std_logic;  -- ufix1
          Encoder_B                       :   OUT   std_logic;  -- ufix1
          Encoder_A                       :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_Subsystem1
    USE ENTITY work.RLUb_HIL_ip_src_Subsystem1(rtl);

  FOR ALL : RLUb_HIL_ip_src_Subsystem2
    USE ENTITY work.RLUb_HIL_ip_src_Subsystem2(rtl);

  FOR ALL : RLUb_HIL_ip_src_Subsystem3
    USE ENTITY work.RLUb_HIL_ip_src_Subsystem3(rtl);

  FOR ALL : RLUb_HIL_ip_src_Subsystem4
    USE ENTITY work.RLUb_HIL_ip_src_Subsystem4(rtl);

  -- Signals
  SIGNAL CntLimit_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL CntLimit_1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Subsystem1_out1_OUT7             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_OUT6             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_OUT5             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_OUT4             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_OUT3             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_OUT2             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_OUT1             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_HILboardRLED     : std_logic;  -- ufix1
  SIGNAL Subsystem2_out1_Status4          : std_logic;  -- ufix1
  SIGNAL Subsystem2_out1_Status3          : std_logic;  -- ufix1
  SIGNAL Subsystem2_out1_Status2          : std_logic;  -- ufix1
  SIGNAL Subsystem2_out1_Status1          : std_logic;  -- ufix1
  SIGNAL Subsystem3_out1_Fail4            : std_logic;  -- ufix1
  SIGNAL Subsystem3_out1_Fail3            : std_logic;  -- ufix1
  SIGNAL Subsystem3_out1_Fail2            : std_logic;  -- ufix1
  SIGNAL Subsystem3_out1_Fail1            : std_logic;  -- ufix1
  SIGNAL Subsystem4_out1_I                : std_logic;  -- ufix1
  SIGNAL Subsystem4_out1_Z                : std_logic;  -- ufix1
  SIGNAL Subsystem4_out1_B                : std_logic;  -- ufix1
  SIGNAL Subsystem4_out1_A                : std_logic;  -- ufix1
  SIGNAL LEDs_unsigned                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL LEDs_1                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Udc_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Udc_1                            : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Ub_unsigned                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Ub_1                             : signed(24 DOWNTO 0);  -- sfix25_En16

BEGIN
  u_Subsystem1 : RLUb_HIL_ip_src_Subsystem1
    PORT MAP( Vio => SlowOut,  -- uint32
              SlowOut_OUT7 => Subsystem1_out1_OUT7,  -- ufix1
              SlowOut_OUT6 => Subsystem1_out1_OUT6,  -- ufix1
              SlowOut_OUT5 => Subsystem1_out1_OUT5,  -- ufix1
              SlowOut_OUT4 => Subsystem1_out1_OUT4,  -- ufix1
              SlowOut_OUT3 => Subsystem1_out1_OUT3,  -- ufix1
              SlowOut_OUT2 => Subsystem1_out1_OUT2,  -- ufix1
              SlowOut_OUT1 => Subsystem1_out1_OUT1,  -- ufix1
              SlowOut_HILboardRLED => Subsystem1_out1_HILboardRLED  -- ufix1
              );

  u_Subsystem2 : RLUb_HIL_ip_src_Subsystem2
    PORT MAP( Vio => Status,  -- uint32
              Status_Status4 => Subsystem2_out1_Status4,  -- ufix1
              Status_Status3 => Subsystem2_out1_Status3,  -- ufix1
              Status_Status2 => Subsystem2_out1_Status2,  -- ufix1
              Status_Status1 => Subsystem2_out1_Status1  -- ufix1
              );

  u_Subsystem3 : RLUb_HIL_ip_src_Subsystem3
    PORT MAP( Vio => Fail,  -- uint32
              Fail_Fail4 => Subsystem3_out1_Fail4,  -- ufix1
              Fail_Fail3 => Subsystem3_out1_Fail3,  -- ufix1
              Fail_Fail2 => Subsystem3_out1_Fail2,  -- ufix1
              Fail_Fail1 => Subsystem3_out1_Fail1  -- ufix1
              );

  u_Subsystem4 : RLUb_HIL_ip_src_Subsystem4
    PORT MAP( Vio => Encoder,  -- uint32
              Encoder_I => Subsystem4_out1_I,  -- ufix1
              Encoder_Z => Subsystem4_out1_Z,  -- ufix1
              Encoder_B => Subsystem4_out1_B,  -- ufix1
              Encoder_A => Subsystem4_out1_A  -- ufix1
              );

  CntLimit_unsigned <= unsigned(CntLimit);

  CntLimit_1 <= CntLimit_unsigned(15 DOWNTO 0);

  Params_CntLimit <= std_logic_vector(CntLimit_1);

  LEDs_unsigned <= unsigned(LEDs);

  LEDs_1 <= LEDs_unsigned(3 DOWNTO 0);

  Params_LEDs <= std_logic_vector(LEDs_1);

  Udc_unsigned <= unsigned(Udc);

  Udc_1 <= signed(Udc_unsigned(24 DOWNTO 0));

  Params_Udc <= std_logic_vector(Udc_1);

  Ub_unsigned <= unsigned(Ub);

  Ub_1 <= signed(Ub_unsigned(24 DOWNTO 0));

  Params_Ub <= std_logic_vector(Ub_1);

  Params_SlowOut_OUT7 <= Subsystem1_out1_OUT7;

  Params_SlowOut_OUT6 <= Subsystem1_out1_OUT6;

  Params_SlowOut_OUT5 <= Subsystem1_out1_OUT5;

  Params_SlowOut_OUT4 <= Subsystem1_out1_OUT4;

  Params_SlowOut_OUT3 <= Subsystem1_out1_OUT3;

  Params_SlowOut_OUT2 <= Subsystem1_out1_OUT2;

  Params_SlowOut_OUT1 <= Subsystem1_out1_OUT1;

  Params_SlowOut_HILboardRLED <= Subsystem1_out1_HILboardRLED;

  Params_Status_Status4 <= Subsystem2_out1_Status4;

  Params_Status_Status3 <= Subsystem2_out1_Status3;

  Params_Status_Status2 <= Subsystem2_out1_Status2;

  Params_Status_Status1 <= Subsystem2_out1_Status1;

  Params_Fail_Fail4 <= Subsystem3_out1_Fail4;

  Params_Fail_Fail3 <= Subsystem3_out1_Fail3;

  Params_Fail_Fail2 <= Subsystem3_out1_Fail2;

  Params_Fail_Fail1 <= Subsystem3_out1_Fail1;

  Params_Encoder_I <= Subsystem4_out1_I;

  Params_Encoder_Z <= Subsystem4_out1_Z;

  Params_Encoder_B <= Subsystem4_out1_B;

  Params_Encoder_A <= Subsystem4_out1_A;

END rtl;

