-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Sigma_Delta.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Sigma_Delta
-- Source Path: RLUb_HIL/AmerOutputs/Sigma Delta
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.RLUb_HIL_ip_src_RLUb_HIL_pkg.ALL;

ENTITY RLUb_HIL_ip_src_Sigma_Delta IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        value                             :   IN    vector_of_std_logic_vector16(0 TO 15);  -- uint16 [16]
        out_rsvd                          :   OUT   std_logic_vector(0 TO 15)  -- boolean [16]
        );
END RLUb_HIL_ip_src_Sigma_Delta;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Sigma_Delta IS

  -- Signals
  SIGNAL value_unsigned                   : vector_of_unsigned16(0 TO 15);  -- uint16 [16]
  SIGNAL Constant_out1                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB1_out1                        : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL bitMask_for_MSB                  : vector_of_unsigned17(0 TO 15);  -- ufix17 [16]
  SIGNAL MSB_out1                         : vector_of_unsigned17(0 TO 15);  -- ufix17 [16]
  SIGNAL MSB_out1_15                      : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_16                : std_logic;
  SIGNAL Switch_out1_15                   : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_14                      : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_15                : std_logic;
  SIGNAL Switch_out1_14                   : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_13                      : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_14                : std_logic;
  SIGNAL Switch_out1_13                   : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_12                      : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_13                : std_logic;
  SIGNAL Switch_out1_12                   : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_11                      : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_12                : std_logic;
  SIGNAL Switch_out1_11                   : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_10                      : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_11                : std_logic;
  SIGNAL Switch_out1_10                   : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_9                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_10                : std_logic;
  SIGNAL Switch_out1_9                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_8                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_9                 : std_logic;
  SIGNAL Switch_out1_8                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_7                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_8                 : std_logic;
  SIGNAL Switch_out1_7                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_6                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_7                 : std_logic;
  SIGNAL Switch_out1_6                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_5                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_6                 : std_logic;
  SIGNAL Switch_out1_5                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_4                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_5                 : std_logic;
  SIGNAL Switch_out1_4                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_3                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_4                 : std_logic;
  SIGNAL Switch_out1_3                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_2                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_3                 : std_logic;
  SIGNAL Switch_out1_2                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_1                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_2                 : std_logic;
  SIGNAL Switch_out1_1                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL MSB_out1_0                       : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Switch_out1_0                    : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL Switch_out1                      : vector_of_unsigned17(0 TO 15);  -- ufix17 [16]
  SIGNAL Sum1_out1                        : vector_of_unsigned17(0 TO 15);  -- ufix17 [16]
  SIGNAL Unit_Delay_out1                  : vector_of_unsigned17(0 TO 15);  -- ufix17 [16]
  SIGNAL Sum_out1                         : vector_of_unsigned17(0 TO 15);  -- ufix17 [16]
  SIGNAL Compare_To_Zero_out1             : std_logic_vector(0 TO 15);  -- boolean [16]

BEGIN
  outputgen: FOR k IN 0 TO 15 GENERATE
    value_unsigned(k) <= unsigned(value(k));
  END GENERATE;

  Constant_out1 <= to_unsigned(16#00000#, 17);

  MSB1_out1 <= to_unsigned(16#10000#, 17);

  bitMask_for_MSB(0) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(1) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(2) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(3) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(4) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(5) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(6) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(7) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(8) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(9) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(10) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(11) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(12) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(13) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(14) <= to_unsigned(16#10000#, 17);
  bitMask_for_MSB(15) <= to_unsigned(16#10000#, 17);

  MSB_out1_15 <= MSB_out1(15);

  
  switch_compare_16 <= '1' WHEN MSB_out1_15 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_15 <= Constant_out1 WHEN switch_compare_16 = '0' ELSE
      MSB1_out1;

  MSB_out1_14 <= MSB_out1(14);

  
  switch_compare_15 <= '1' WHEN MSB_out1_14 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_14 <= Constant_out1 WHEN switch_compare_15 = '0' ELSE
      MSB1_out1;

  MSB_out1_13 <= MSB_out1(13);

  
  switch_compare_14 <= '1' WHEN MSB_out1_13 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_13 <= Constant_out1 WHEN switch_compare_14 = '0' ELSE
      MSB1_out1;

  MSB_out1_12 <= MSB_out1(12);

  
  switch_compare_13 <= '1' WHEN MSB_out1_12 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_12 <= Constant_out1 WHEN switch_compare_13 = '0' ELSE
      MSB1_out1;

  MSB_out1_11 <= MSB_out1(11);

  
  switch_compare_12 <= '1' WHEN MSB_out1_11 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_11 <= Constant_out1 WHEN switch_compare_12 = '0' ELSE
      MSB1_out1;

  MSB_out1_10 <= MSB_out1(10);

  
  switch_compare_11 <= '1' WHEN MSB_out1_10 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_10 <= Constant_out1 WHEN switch_compare_11 = '0' ELSE
      MSB1_out1;

  MSB_out1_9 <= MSB_out1(9);

  
  switch_compare_10 <= '1' WHEN MSB_out1_9 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_9 <= Constant_out1 WHEN switch_compare_10 = '0' ELSE
      MSB1_out1;

  MSB_out1_8 <= MSB_out1(8);

  
  switch_compare_9 <= '1' WHEN MSB_out1_8 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_8 <= Constant_out1 WHEN switch_compare_9 = '0' ELSE
      MSB1_out1;

  MSB_out1_7 <= MSB_out1(7);

  
  switch_compare_8 <= '1' WHEN MSB_out1_7 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_7 <= Constant_out1 WHEN switch_compare_8 = '0' ELSE
      MSB1_out1;

  MSB_out1_6 <= MSB_out1(6);

  
  switch_compare_7 <= '1' WHEN MSB_out1_6 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_6 <= Constant_out1 WHEN switch_compare_7 = '0' ELSE
      MSB1_out1;

  MSB_out1_5 <= MSB_out1(5);

  
  switch_compare_6 <= '1' WHEN MSB_out1_5 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_5 <= Constant_out1 WHEN switch_compare_6 = '0' ELSE
      MSB1_out1;

  MSB_out1_4 <= MSB_out1(4);

  
  switch_compare_5 <= '1' WHEN MSB_out1_4 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_4 <= Constant_out1 WHEN switch_compare_5 = '0' ELSE
      MSB1_out1;

  MSB_out1_3 <= MSB_out1(3);

  
  switch_compare_4 <= '1' WHEN MSB_out1_3 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_3 <= Constant_out1 WHEN switch_compare_4 = '0' ELSE
      MSB1_out1;

  MSB_out1_2 <= MSB_out1(2);

  
  switch_compare_3 <= '1' WHEN MSB_out1_2 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_2 <= Constant_out1 WHEN switch_compare_3 = '0' ELSE
      MSB1_out1;

  MSB_out1_1 <= MSB_out1(1);

  
  switch_compare_2 <= '1' WHEN MSB_out1_1 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_1 <= Constant_out1 WHEN switch_compare_2 = '0' ELSE
      MSB1_out1;

  MSB_out1_0 <= MSB_out1(0);

  
  switch_compare_1 <= '1' WHEN MSB_out1_0 > to_unsigned(16#00000#, 17) ELSE
      '0';

  
  Switch_out1_0 <= Constant_out1 WHEN switch_compare_1 = '0' ELSE
      MSB1_out1;

  Switch_out1(0) <= Switch_out1_0;
  Switch_out1(1) <= Switch_out1_1;
  Switch_out1(2) <= Switch_out1_2;
  Switch_out1(3) <= Switch_out1_3;
  Switch_out1(4) <= Switch_out1_4;
  Switch_out1(5) <= Switch_out1_5;
  Switch_out1(6) <= Switch_out1_6;
  Switch_out1(7) <= Switch_out1_7;
  Switch_out1(8) <= Switch_out1_8;
  Switch_out1(9) <= Switch_out1_9;
  Switch_out1(10) <= Switch_out1_10;
  Switch_out1(11) <= Switch_out1_11;
  Switch_out1(12) <= Switch_out1_12;
  Switch_out1(13) <= Switch_out1_13;
  Switch_out1(14) <= Switch_out1_14;
  Switch_out1(15) <= Switch_out1_15;


  Sum1_out1_gen: FOR t_0 IN 0 TO 15 GENERATE
    Sum1_out1(t_0) <= resize(value_unsigned(t_0), 17) - Switch_out1(t_0);
  END GENERATE Sum1_out1_gen;



  Sum_out1_gen: FOR t_01 IN 0 TO 15 GENERATE
    Sum_out1(t_01) <= Sum1_out1(t_01) + Unit_Delay_out1(t_01);
  END GENERATE Sum_out1_gen;


  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= (OTHERS => to_unsigned(16#00000#, 17));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Sum_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;



  MSB_out1_gen: FOR t_02 IN 0 TO 15 GENERATE
    MSB_out1(t_02) <= Unit_Delay_out1(t_02) AND bitMask_for_MSB(t_02);
  END GENERATE MSB_out1_gen;



  Compare_To_Zero_out1_gen: FOR t_03 IN 0 TO 15 GENERATE
    
    Compare_To_Zero_out1(t_03) <= '1' WHEN MSB_out1(t_03) > to_unsigned(16#00000#, 17) ELSE
        '0';
  END GENERATE Compare_To_Zero_out1_gen;


  out_rsvd <= Compare_To_Zero_out1;

END rtl;

