-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_Subsystem1_block.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_Subsystem1_block
-- Source Path: RLUb_HIL/SignalMUX/Subsystem1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_Subsystem1_block IS
  PORT( In1                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        LED_LED3                          :   OUT   std_logic;  -- ufix1
        LED_LED2                          :   OUT   std_logic;  -- ufix1
        LED_LED1                          :   OUT   std_logic;  -- ufix1
        LED_LED0                          :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_Subsystem1_block;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_Subsystem1_block IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL LED3                             : std_logic;  -- ufix1
  SIGNAL LED2                             : std_logic;  -- ufix1
  SIGNAL LED1                             : std_logic;  -- ufix1
  SIGNAL LED0                             : std_logic;  -- ufix1

BEGIN
  In1_unsigned <= unsigned(In1);

  LED3 <= In1_unsigned(3);

  LED2 <= In1_unsigned(2);

  LED1 <= In1_unsigned(1);

  LED0 <= In1_unsigned(0);

  LED_LED3 <= LED3;

  LED_LED2 <= LED2;

  LED_LED1 <= LED1;

  LED_LED0 <= LED0;

END rtl;

