-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_HitermOutputs.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_HitermOutputs
-- Source Path: RLUb_HIL/HitermOutputs
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RLUb_HIL_ip_src_HitermOutputs IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AmerIn_ZyboBTN_BTN3               :   IN    std_logic;  -- ufix1
        AmerIn_ZyboBTN_BTN2               :   IN    std_logic;  -- ufix1
        AmerIn_ZyboBTN_BTN1               :   IN    std_logic;  -- ufix1
        AmerIn_ZyboSW_SW3                 :   IN    std_logic;  -- ufix1
        AmerIn_ZyboSW_SW2                 :   IN    std_logic;  -- ufix1
        AmerIn_ZyboSW_SW1                 :   IN    std_logic;  -- ufix1
        AmerIn_ZyboSW_SW0                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H4                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H3                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H2                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GH_H1                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L4                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L3                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L2                 :   IN    std_logic;  -- ufix1
        AmerIn_Ctrl_GL_L1                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN7                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN6                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN5                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN4                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN3                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN2                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_IN1                 :   IN    std_logic;  -- ufix1
        AmerIn_SlowIn_HILboardSW          :   IN    std_logic;  -- ufix1
        ModelOut_Iout                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
        ModelOut_Vout                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        ModelOut_Udc                      :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        ModelOut_Ub                       :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        Params_CntLimit                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Params_SlowOut_OUT7               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT6               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT5               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT4               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT3               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT2               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT1               :   IN    std_logic;  -- ufix1
        Params_SlowOut_HILboardRLED       :   IN    std_logic;  -- ufix1
        Params_Status_Status4             :   IN    std_logic;  -- ufix1
        Params_Status_Status3             :   IN    std_logic;  -- ufix1
        Params_Status_Status2             :   IN    std_logic;  -- ufix1
        Params_Status_Status1             :   IN    std_logic;  -- ufix1
        Params_Fail_Fail4                 :   IN    std_logic;  -- ufix1
        Params_Fail_Fail3                 :   IN    std_logic;  -- ufix1
        Params_Fail_Fail2                 :   IN    std_logic;  -- ufix1
        Params_Fail_Fail1                 :   IN    std_logic;  -- ufix1
        Params_Encoder_I                  :   IN    std_logic;  -- ufix1
        Params_Encoder_Z                  :   IN    std_logic;  -- ufix1
        Params_Encoder_B                  :   IN    std_logic;  -- ufix1
        Params_Encoder_A                  :   IN    std_logic;  -- ufix1
        Params_LEDs                       :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        Params_Udc                        :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        Params_Ub                         :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        Cnt                               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        SW                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        SlowIn                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Iout                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Vout                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END RLUb_HIL_ip_src_HitermOutputs;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_HitermOutputs IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_Counter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          limit                           :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Cnt                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_Counter
    USE ENTITY work.RLUb_HIL_ip_src_Counter(rtl);

  -- Signals
  SIGNAL CntLimit                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Counter_out1                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Counter_out1_unsigned            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Data_Type_Conversion4_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bus_to_Vector5_out1              : std_logic_vector(0 TO 3);  -- ufix1 [4]
  SIGNAL Bit_Concat6_out1                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Data_Type_Conversion5_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bus_to_Vector6_out1              : std_logic_vector(0 TO 7);  -- ufix1 [8]
  SIGNAL Bit_Concat7_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Data_Type_Conversion6_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Iout_1                           : signed(24 DOWNTO 0);  -- sfix25_En17
  SIGNAL Data_Type_Conversion1_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Vout_1                           : signed(24 DOWNTO 0);  -- sfix25_En16
  SIGNAL Data_Type_Conversion2_out1       : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_Counter : RLUb_HIL_ip_src_Counter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              limit => std_logic_vector(CntLimit),  -- uint16
              Cnt => Counter_out1  -- uint16
              );

  CntLimit <= unsigned(Params_CntLimit);

  Counter_out1_unsigned <= unsigned(Counter_out1);

  Data_Type_Conversion4_out1 <= resize(Counter_out1_unsigned, 32);

  Cnt <= std_logic_vector(Data_Type_Conversion4_out1);

  Bus_to_Vector5_out1(0) <= AmerIn_ZyboSW_SW3;
  Bus_to_Vector5_out1(1) <= AmerIn_ZyboSW_SW2;
  Bus_to_Vector5_out1(2) <= AmerIn_ZyboSW_SW1;
  Bus_to_Vector5_out1(3) <= AmerIn_ZyboSW_SW0;

  Bit_Concat6_out1 <= unsigned'(Bus_to_Vector5_out1(0) & Bus_to_Vector5_out1(1) & Bus_to_Vector5_out1(2) & Bus_to_Vector5_out1(3));

  Data_Type_Conversion5_out1 <= resize(Bit_Concat6_out1, 32);

  SW <= std_logic_vector(Data_Type_Conversion5_out1);

  Bus_to_Vector6_out1(0) <= AmerIn_SlowIn_IN7;
  Bus_to_Vector6_out1(1) <= AmerIn_SlowIn_IN6;
  Bus_to_Vector6_out1(2) <= AmerIn_SlowIn_IN5;
  Bus_to_Vector6_out1(3) <= AmerIn_SlowIn_IN4;
  Bus_to_Vector6_out1(4) <= AmerIn_SlowIn_IN3;
  Bus_to_Vector6_out1(5) <= AmerIn_SlowIn_IN2;
  Bus_to_Vector6_out1(6) <= AmerIn_SlowIn_IN1;
  Bus_to_Vector6_out1(7) <= AmerIn_SlowIn_HILboardSW;

  Bit_Concat7_out1 <= unsigned'(Bus_to_Vector6_out1(0) & Bus_to_Vector6_out1(1) & Bus_to_Vector6_out1(2) & Bus_to_Vector6_out1(3) & Bus_to_Vector6_out1(4) & Bus_to_Vector6_out1(5) & Bus_to_Vector6_out1(6) & Bus_to_Vector6_out1(7));

  Data_Type_Conversion6_out1 <= resize(Bit_Concat7_out1, 32);

  SlowIn <= std_logic_vector(Data_Type_Conversion6_out1);

  Iout_1 <= signed(ModelOut_Iout);

  Data_Type_Conversion1_out1 <= unsigned(resize(Iout_1, 32));

  Iout <= std_logic_vector(Data_Type_Conversion1_out1);

  Vout_1 <= signed(ModelOut_Vout);

  Data_Type_Conversion2_out1 <= unsigned(resize(Vout_1, 32));

  Vout <= std_logic_vector(Data_Type_Conversion2_out1);

END rtl;

