-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\RLUb_HIL\RLUb_HIL_ip_src_SignalMUX.vhd
-- Created: 2026-03-27 14:58:45
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RLUb_HIL_ip_src_SignalMUX
-- Source Path: RLUb_HIL/SignalMUX
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.RLUb_HIL_ip_src_RLUb_HIL_pkg.ALL;

ENTITY RLUb_HIL_ip_src_SignalMUX IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        ModelOut_Iout                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
        ModelOut_Vout                     :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        ModelOut_Udc                      :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        ModelOut_Ub                       :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        Params_CntLimit                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Params_SlowOut_OUT7               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT6               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT5               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT4               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT3               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT2               :   IN    std_logic;  -- ufix1
        Params_SlowOut_OUT1               :   IN    std_logic;  -- ufix1
        Params_SlowOut_HILboardRLED       :   IN    std_logic;  -- ufix1
        Params_Status_Status4             :   IN    std_logic;  -- ufix1
        Params_Status_Status3             :   IN    std_logic;  -- ufix1
        Params_Status_Status2             :   IN    std_logic;  -- ufix1
        Params_Status_Status1             :   IN    std_logic;  -- ufix1
        Params_Fail_Fail4                 :   IN    std_logic;  -- ufix1
        Params_Fail_Fail3                 :   IN    std_logic;  -- ufix1
        Params_Fail_Fail2                 :   IN    std_logic;  -- ufix1
        Params_Fail_Fail1                 :   IN    std_logic;  -- ufix1
        Params_Encoder_I                  :   IN    std_logic;  -- ufix1
        Params_Encoder_Z                  :   IN    std_logic;  -- ufix1
        Params_Encoder_B                  :   IN    std_logic;  -- ufix1
        Params_Encoder_A                  :   IN    std_logic;  -- ufix1
        Params_LEDs                       :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        Params_Udc                        :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        Params_Ub                         :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
        AmerOut_ANA_CH7                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH6                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH5                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH4                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH3                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH2                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH1                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANA_CH0                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH7                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH6                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH5                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH4                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH3                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH2                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH1                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_ANB_CH0                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        AmerOut_SlowOut_OUT7              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_OUT6              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_OUT5              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_OUT4              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_OUT3              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_OUT2              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_OUT1              :   OUT   std_logic;  -- ufix1
        AmerOut_SlowOut_HILboardRLED      :   OUT   std_logic;  -- ufix1
        AmerOut_Status_Status4            :   OUT   std_logic;  -- ufix1
        AmerOut_Status_Status3            :   OUT   std_logic;  -- ufix1
        AmerOut_Status_Status2            :   OUT   std_logic;  -- ufix1
        AmerOut_Status_Status1            :   OUT   std_logic;  -- ufix1
        AmerOut_Fail_Fail4                :   OUT   std_logic;  -- ufix1
        AmerOut_Fail_Fail3                :   OUT   std_logic;  -- ufix1
        AmerOut_Fail_Fail2                :   OUT   std_logic;  -- ufix1
        AmerOut_Fail_Fail1                :   OUT   std_logic;  -- ufix1
        AmerOut_Encoder_I                 :   OUT   std_logic;  -- ufix1
        AmerOut_Encoder_Z                 :   OUT   std_logic;  -- ufix1
        AmerOut_Encoder_B                 :   OUT   std_logic;  -- ufix1
        AmerOut_Encoder_A                 :   OUT   std_logic;  -- ufix1
        AmerOut_ZyboLED_LED3              :   OUT   std_logic;  -- ufix1
        AmerOut_ZyboLED_LED2              :   OUT   std_logic;  -- ufix1
        AmerOut_ZyboLED_LED1              :   OUT   std_logic;  -- ufix1
        AmerOut_ZyboLED_LED0              :   OUT   std_logic  -- ufix1
        );
END RLUb_HIL_ip_src_SignalMUX;


ARCHITECTURE rtl OF RLUb_HIL_ip_src_SignalMUX IS

  -- Component Declarations
  COMPONENT RLUb_HIL_ip_src_AnalogOut
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          model_out_Iout                  :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En17
          model_out_Vout                  :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          model_out_Udc                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          model_out_Ub                    :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En16
          ANA_CH7                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH6                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH5                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH4                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH3                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH1                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANA_CH0                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH7                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH6                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH5                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH4                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH3                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH1                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          ANB_CH0                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT RLUb_HIL_ip_src_Subsystem1_block
    PORT( In1                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          LED_LED3                        :   OUT   std_logic;  -- ufix1
          LED_LED2                        :   OUT   std_logic;  -- ufix1
          LED_LED1                        :   OUT   std_logic;  -- ufix1
          LED_LED0                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RLUb_HIL_ip_src_AnalogOut
    USE ENTITY work.RLUb_HIL_ip_src_AnalogOut(rtl);

  FOR ALL : RLUb_HIL_ip_src_Subsystem1_block
    USE ENTITY work.RLUb_HIL_ip_src_Subsystem1_block(rtl);

  -- Signals
  SIGNAL AnalogOut_out1_CH7               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH6               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH5               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH4               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH3               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH2               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out1_CH0               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH7               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH6               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH5               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH4               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH3               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH2               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH0               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL AnalogOut_out2_CH7_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg                        : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH7_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH6_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_1                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH6_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH5_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_2                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH5_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH4_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_3                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH4_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH3_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_4                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH3_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH2_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_5                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH2_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH1_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_6                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH1_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL AnalogOut_out2_CH0_unsigned      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_7                      : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL AnalogOut_out2_CH0_1             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha_reg_8                      : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT7                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_9                      : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT6                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_10                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT5                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_11                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT4                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_12                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT3                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_13                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT2                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_14                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_OUT1                     : std_logic;  -- ufix1
  SIGNAL alpha_reg_15                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL SlowOut_HILboardRLED             : std_logic;  -- ufix1
  SIGNAL alpha_reg_16                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Status_Status4                   : std_logic;  -- ufix1
  SIGNAL alpha_reg_17                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Status_Status3                   : std_logic;  -- ufix1
  SIGNAL alpha_reg_18                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Status_Status2                   : std_logic;  -- ufix1
  SIGNAL alpha_reg_19                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Status_Status1                   : std_logic;  -- ufix1
  SIGNAL alpha_reg_20                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Fail_Fail4                       : std_logic;  -- ufix1
  SIGNAL alpha_reg_21                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Fail_Fail3                       : std_logic;  -- ufix1
  SIGNAL alpha_reg_22                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Fail_Fail2                       : std_logic;  -- ufix1
  SIGNAL alpha_reg_23                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Fail_Fail1                       : std_logic;  -- ufix1
  SIGNAL alpha_reg_24                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Encoder_I                        : std_logic;  -- ufix1
  SIGNAL alpha_reg_25                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Encoder_Z                        : std_logic;  -- ufix1
  SIGNAL alpha_reg_26                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Encoder_B                        : std_logic;  -- ufix1
  SIGNAL alpha_reg_27                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Encoder_A                        : std_logic;  -- ufix1
  SIGNAL LEDs                             : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Subsystem1_out1_LED3             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_LED2             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_LED1             : std_logic;  -- ufix1
  SIGNAL Subsystem1_out1_LED0             : std_logic;  -- ufix1
  SIGNAL alpha_reg_28                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Subsystem1_out1_LED3_1           : std_logic;  -- ufix1
  SIGNAL alpha_reg_29                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Subsystem1_out1_LED2_1           : std_logic;  -- ufix1
  SIGNAL alpha_reg_30                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Subsystem1_out1_LED1_1           : std_logic;  -- ufix1
  SIGNAL alpha_reg_31                     : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Subsystem1_out1_LED0_1           : std_logic;  -- ufix1

BEGIN
  u_AnalogOut : RLUb_HIL_ip_src_AnalogOut
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              model_out_Iout => ModelOut_Iout,  -- sfix25_En17
              model_out_Vout => ModelOut_Vout,  -- sfix25_En16
              model_out_Udc => ModelOut_Udc,  -- sfix25_En16
              model_out_Ub => ModelOut_Ub,  -- sfix25_En16
              ANA_CH7 => AnalogOut_out1_CH7,  -- uint16
              ANA_CH6 => AnalogOut_out1_CH6,  -- uint16
              ANA_CH5 => AnalogOut_out1_CH5,  -- uint16
              ANA_CH4 => AnalogOut_out1_CH4,  -- uint16
              ANA_CH3 => AnalogOut_out1_CH3,  -- uint16
              ANA_CH2 => AnalogOut_out1_CH2,  -- uint16
              ANA_CH1 => AnalogOut_out1_CH1,  -- uint16
              ANA_CH0 => AnalogOut_out1_CH0,  -- uint16
              ANB_CH7 => AnalogOut_out2_CH7,  -- uint16
              ANB_CH6 => AnalogOut_out2_CH6,  -- uint16
              ANB_CH5 => AnalogOut_out2_CH5,  -- uint16
              ANB_CH4 => AnalogOut_out2_CH4,  -- uint16
              ANB_CH3 => AnalogOut_out2_CH3,  -- uint16
              ANB_CH2 => AnalogOut_out2_CH2,  -- uint16
              ANB_CH1 => AnalogOut_out2_CH1,  -- uint16
              ANB_CH0 => AnalogOut_out2_CH0  -- uint16
              );

  u_Subsystem1 : RLUb_HIL_ip_src_Subsystem1_block
    PORT MAP( In1 => std_logic_vector(LEDs),  -- ufix4
              LED_LED3 => Subsystem1_out1_LED3,  -- ufix1
              LED_LED2 => Subsystem1_out1_LED2,  -- ufix1
              LED_LED1 => Subsystem1_out1_LED1,  -- ufix1
              LED_LED0 => Subsystem1_out1_LED0  -- ufix1
              );

  AnalogOut_out2_CH7_unsigned <= unsigned(AnalogOut_out2_CH7);

  c_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg(0) <= AnalogOut_out2_CH7_unsigned;
        alpha_reg(1) <= alpha_reg(0);
      END IF;
    END IF;
  END PROCESS c_process;

  AnalogOut_out2_CH7_1 <= alpha_reg(1);

  AmerOut_ANB_CH7 <= std_logic_vector(AnalogOut_out2_CH7_1);

  AnalogOut_out2_CH6_unsigned <= unsigned(AnalogOut_out2_CH6);

  c_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_1 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_1(0) <= AnalogOut_out2_CH6_unsigned;
        alpha_reg_1(1) <= alpha_reg_1(0);
      END IF;
    END IF;
  END PROCESS c_1_process;

  AnalogOut_out2_CH6_1 <= alpha_reg_1(1);

  AmerOut_ANB_CH6 <= std_logic_vector(AnalogOut_out2_CH6_1);

  AnalogOut_out2_CH5_unsigned <= unsigned(AnalogOut_out2_CH5);

  c_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_2 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_2(0) <= AnalogOut_out2_CH5_unsigned;
        alpha_reg_2(1) <= alpha_reg_2(0);
      END IF;
    END IF;
  END PROCESS c_2_process;

  AnalogOut_out2_CH5_1 <= alpha_reg_2(1);

  AmerOut_ANB_CH5 <= std_logic_vector(AnalogOut_out2_CH5_1);

  AnalogOut_out2_CH4_unsigned <= unsigned(AnalogOut_out2_CH4);

  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_3 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_3(0) <= AnalogOut_out2_CH4_unsigned;
        alpha_reg_3(1) <= alpha_reg_3(0);
      END IF;
    END IF;
  END PROCESS c_3_process;

  AnalogOut_out2_CH4_1 <= alpha_reg_3(1);

  AmerOut_ANB_CH4 <= std_logic_vector(AnalogOut_out2_CH4_1);

  AnalogOut_out2_CH3_unsigned <= unsigned(AnalogOut_out2_CH3);

  c_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_4 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_4(0) <= AnalogOut_out2_CH3_unsigned;
        alpha_reg_4(1) <= alpha_reg_4(0);
      END IF;
    END IF;
  END PROCESS c_4_process;

  AnalogOut_out2_CH3_1 <= alpha_reg_4(1);

  AmerOut_ANB_CH3 <= std_logic_vector(AnalogOut_out2_CH3_1);

  AnalogOut_out2_CH2_unsigned <= unsigned(AnalogOut_out2_CH2);

  c_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_5 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_5(0) <= AnalogOut_out2_CH2_unsigned;
        alpha_reg_5(1) <= alpha_reg_5(0);
      END IF;
    END IF;
  END PROCESS c_5_process;

  AnalogOut_out2_CH2_1 <= alpha_reg_5(1);

  AmerOut_ANB_CH2 <= std_logic_vector(AnalogOut_out2_CH2_1);

  AnalogOut_out2_CH1_unsigned <= unsigned(AnalogOut_out2_CH1);

  c_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_6 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_6(0) <= AnalogOut_out2_CH1_unsigned;
        alpha_reg_6(1) <= alpha_reg_6(0);
      END IF;
    END IF;
  END PROCESS c_6_process;

  AnalogOut_out2_CH1_1 <= alpha_reg_6(1);

  AmerOut_ANB_CH1 <= std_logic_vector(AnalogOut_out2_CH1_1);

  AnalogOut_out2_CH0_unsigned <= unsigned(AnalogOut_out2_CH0);

  c_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_7 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_7(0) <= AnalogOut_out2_CH0_unsigned;
        alpha_reg_7(1) <= alpha_reg_7(0);
      END IF;
    END IF;
  END PROCESS c_7_process;

  AnalogOut_out2_CH0_1 <= alpha_reg_7(1);

  AmerOut_ANB_CH0 <= std_logic_vector(AnalogOut_out2_CH0_1);

  c_8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_8 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_8(0) <= Params_SlowOut_OUT7;
        alpha_reg_8(1) <= alpha_reg_8(0);
      END IF;
    END IF;
  END PROCESS c_8_process;

  SlowOut_OUT7 <= alpha_reg_8(1);

  c_9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_9 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_9(0) <= Params_SlowOut_OUT6;
        alpha_reg_9(1) <= alpha_reg_9(0);
      END IF;
    END IF;
  END PROCESS c_9_process;

  SlowOut_OUT6 <= alpha_reg_9(1);

  c_10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_10 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_10(0) <= Params_SlowOut_OUT5;
        alpha_reg_10(1) <= alpha_reg_10(0);
      END IF;
    END IF;
  END PROCESS c_10_process;

  SlowOut_OUT5 <= alpha_reg_10(1);

  c_11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_11 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_11(0) <= Params_SlowOut_OUT4;
        alpha_reg_11(1) <= alpha_reg_11(0);
      END IF;
    END IF;
  END PROCESS c_11_process;

  SlowOut_OUT4 <= alpha_reg_11(1);

  c_12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_12 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_12(0) <= Params_SlowOut_OUT3;
        alpha_reg_12(1) <= alpha_reg_12(0);
      END IF;
    END IF;
  END PROCESS c_12_process;

  SlowOut_OUT3 <= alpha_reg_12(1);

  c_13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_13 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_13(0) <= Params_SlowOut_OUT2;
        alpha_reg_13(1) <= alpha_reg_13(0);
      END IF;
    END IF;
  END PROCESS c_13_process;

  SlowOut_OUT2 <= alpha_reg_13(1);

  c_14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_14 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_14(0) <= Params_SlowOut_OUT1;
        alpha_reg_14(1) <= alpha_reg_14(0);
      END IF;
    END IF;
  END PROCESS c_14_process;

  SlowOut_OUT1 <= alpha_reg_14(1);

  c_15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_15 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_15(0) <= Params_SlowOut_HILboardRLED;
        alpha_reg_15(1) <= alpha_reg_15(0);
      END IF;
    END IF;
  END PROCESS c_15_process;

  SlowOut_HILboardRLED <= alpha_reg_15(1);

  c_16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_16 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_16(0) <= Params_Status_Status4;
        alpha_reg_16(1) <= alpha_reg_16(0);
      END IF;
    END IF;
  END PROCESS c_16_process;

  Status_Status4 <= alpha_reg_16(1);

  c_17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_17 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_17(0) <= Params_Status_Status3;
        alpha_reg_17(1) <= alpha_reg_17(0);
      END IF;
    END IF;
  END PROCESS c_17_process;

  Status_Status3 <= alpha_reg_17(1);

  c_18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_18 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_18(0) <= Params_Status_Status2;
        alpha_reg_18(1) <= alpha_reg_18(0);
      END IF;
    END IF;
  END PROCESS c_18_process;

  Status_Status2 <= alpha_reg_18(1);

  c_19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_19 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_19(0) <= Params_Status_Status1;
        alpha_reg_19(1) <= alpha_reg_19(0);
      END IF;
    END IF;
  END PROCESS c_19_process;

  Status_Status1 <= alpha_reg_19(1);

  c_20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_20 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_20(0) <= Params_Fail_Fail4;
        alpha_reg_20(1) <= alpha_reg_20(0);
      END IF;
    END IF;
  END PROCESS c_20_process;

  Fail_Fail4 <= alpha_reg_20(1);

  c_21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_21 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_21(0) <= Params_Fail_Fail3;
        alpha_reg_21(1) <= alpha_reg_21(0);
      END IF;
    END IF;
  END PROCESS c_21_process;

  Fail_Fail3 <= alpha_reg_21(1);

  c_22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_22 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_22(0) <= Params_Fail_Fail2;
        alpha_reg_22(1) <= alpha_reg_22(0);
      END IF;
    END IF;
  END PROCESS c_22_process;

  Fail_Fail2 <= alpha_reg_22(1);

  c_23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_23 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_23(0) <= Params_Fail_Fail1;
        alpha_reg_23(1) <= alpha_reg_23(0);
      END IF;
    END IF;
  END PROCESS c_23_process;

  Fail_Fail1 <= alpha_reg_23(1);

  c_24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_24 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_24(0) <= Params_Encoder_I;
        alpha_reg_24(1) <= alpha_reg_24(0);
      END IF;
    END IF;
  END PROCESS c_24_process;

  Encoder_I <= alpha_reg_24(1);

  c_25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_25 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_25(0) <= Params_Encoder_Z;
        alpha_reg_25(1) <= alpha_reg_25(0);
      END IF;
    END IF;
  END PROCESS c_25_process;

  Encoder_Z <= alpha_reg_25(1);

  c_26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_26 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_26(0) <= Params_Encoder_B;
        alpha_reg_26(1) <= alpha_reg_26(0);
      END IF;
    END IF;
  END PROCESS c_26_process;

  Encoder_B <= alpha_reg_26(1);

  c_27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_27 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_27(0) <= Params_Encoder_A;
        alpha_reg_27(1) <= alpha_reg_27(0);
      END IF;
    END IF;
  END PROCESS c_27_process;

  Encoder_A <= alpha_reg_27(1);

  LEDs <= unsigned(Params_LEDs);

  c_28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_28 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_28(0) <= Subsystem1_out1_LED3;
        alpha_reg_28(1) <= alpha_reg_28(0);
      END IF;
    END IF;
  END PROCESS c_28_process;

  Subsystem1_out1_LED3_1 <= alpha_reg_28(1);

  c_29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_29 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_29(0) <= Subsystem1_out1_LED2;
        alpha_reg_29(1) <= alpha_reg_29(0);
      END IF;
    END IF;
  END PROCESS c_29_process;

  Subsystem1_out1_LED2_1 <= alpha_reg_29(1);

  c_30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_30 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_30(0) <= Subsystem1_out1_LED1;
        alpha_reg_30(1) <= alpha_reg_30(0);
      END IF;
    END IF;
  END PROCESS c_30_process;

  Subsystem1_out1_LED1_1 <= alpha_reg_30(1);

  c_31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_31 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_31(0) <= Subsystem1_out1_LED0;
        alpha_reg_31(1) <= alpha_reg_31(0);
      END IF;
    END IF;
  END PROCESS c_31_process;

  Subsystem1_out1_LED0_1 <= alpha_reg_31(1);

  AmerOut_ANA_CH7 <= AnalogOut_out1_CH7;

  AmerOut_ANA_CH6 <= AnalogOut_out1_CH6;

  AmerOut_ANA_CH5 <= AnalogOut_out1_CH5;

  AmerOut_ANA_CH4 <= AnalogOut_out1_CH4;

  AmerOut_ANA_CH3 <= AnalogOut_out1_CH3;

  AmerOut_ANA_CH2 <= AnalogOut_out1_CH2;

  AmerOut_ANA_CH1 <= AnalogOut_out1_CH1;

  AmerOut_ANA_CH0 <= AnalogOut_out1_CH0;

  AmerOut_SlowOut_OUT7 <= SlowOut_OUT7;

  AmerOut_SlowOut_OUT6 <= SlowOut_OUT6;

  AmerOut_SlowOut_OUT5 <= SlowOut_OUT5;

  AmerOut_SlowOut_OUT4 <= SlowOut_OUT4;

  AmerOut_SlowOut_OUT3 <= SlowOut_OUT3;

  AmerOut_SlowOut_OUT2 <= SlowOut_OUT2;

  AmerOut_SlowOut_OUT1 <= SlowOut_OUT1;

  AmerOut_SlowOut_HILboardRLED <= SlowOut_HILboardRLED;

  AmerOut_Status_Status4 <= Status_Status4;

  AmerOut_Status_Status3 <= Status_Status3;

  AmerOut_Status_Status2 <= Status_Status2;

  AmerOut_Status_Status1 <= Status_Status1;

  AmerOut_Fail_Fail4 <= Fail_Fail4;

  AmerOut_Fail_Fail3 <= Fail_Fail3;

  AmerOut_Fail_Fail2 <= Fail_Fail2;

  AmerOut_Fail_Fail1 <= Fail_Fail1;

  AmerOut_Encoder_I <= Encoder_I;

  AmerOut_Encoder_Z <= Encoder_Z;

  AmerOut_Encoder_B <= Encoder_B;

  AmerOut_Encoder_A <= Encoder_A;

  AmerOut_ZyboLED_LED3 <= Subsystem1_out1_LED3_1;

  AmerOut_ZyboLED_LED2 <= Subsystem1_out1_LED2_1;

  AmerOut_ZyboLED_LED1 <= Subsystem1_out1_LED1_1;

  AmerOut_ZyboLED_LED0 <= Subsystem1_out1_LED0_1;

END rtl;

